package io.tlobjects.tl.api.auth;

import static io.tlobjects.tl.StreamUtils.*;
import static io.tlobjects.tl.TLObjectUtils.*;

import io.tlobjects.tl.core.TLObject;

/**
 * Abstraction level for the following constructors:
 * <ul>
 * <li>{@link TLCodeTypeCall}: auth.codeTypeCall#741cd3e3</li>
 * <li>{@link TLCodeTypeFlashCall}: auth.codeTypeFlashCall#226ccefb</li>
 * <li>{@link TLCodeTypeSms}: auth.codeTypeSms#72a3158c</li>
 * </ul>
 *
 * This class is generated by Mono's TL class generator
 */
public abstract class TLAbsCodeType extends TLObject {
    public TLAbsCodeType() {
    }
}
