package io.tlobjects.tl.api.auth;

import static io.tlobjects.tl.StreamUtils.*;
import static io.tlobjects.tl.TLObjectUtils.*;

import java.lang.Override;
import java.lang.String;

/**
 * This class is generated by Mono's TL class generator
 */
public class TLCodeTypeCall extends TLAbsCodeType {
    public static final int CONSTRUCTOR_ID = 0x741cd3e3;

    private final String _constructor = "auth.codeTypeCall#741cd3e3";

    public TLCodeTypeCall() {
    }

    @Override
    public String toString() {
        return _constructor;
    }

    @Override
    public int getConstructorId() {
        return CONSTRUCTOR_ID;
    }
}
