package io.objects.tl.api.request;

import io.objects.tl.TLContext;
import io.objects.tl.api.help.TLAbsAppUpdate;
import io.objects.tl.core.TLMethod;
import io.objects.tl.core.TLObject;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;

import static io.objects.tl.StreamUtils.readTLObject;
import static io.objects.tl.TLObjectUtils.SIZE_CONSTRUCTOR_ID;

/**
 * This class is generated by Mono's TL class generator
 */
public class TLRequestHelpGetAppUpdateVios extends TLMethod<TLAbsAppUpdate> {
    public static final int CONSTRUCTOR_ID = 0xae2de196;


    private final String _constructor = "help.getAppUpdateVios#ae2de196";

    public TLRequestHelpGetAppUpdateVios() {
    }


    @Override
    @SuppressWarnings({"unchecked", "SimplifiableConditionalExpression"})
    public TLAbsAppUpdate deserializeResponse(InputStream stream, TLContext context) throws
            IOException {
        final TLObject response = readTLObject(stream, context);
        if (response == null) {
            throw new IOException("Unable to parse response");
        }
        if (!(response instanceof TLAbsAppUpdate)) {
            throw new IOException("Incorrect response type, expected " + getClass().getCanonicalName() + ", found " + response.getClass().getCanonicalName());
        }
        return (TLAbsAppUpdate) response;
    }

    @Override
    public void serializeBody(OutputStream stream) throws IOException {
    }

    @Override
    @SuppressWarnings({"unchecked", "SimplifiableConditionalExpression"})
    public void deserializeBody(InputStream stream, TLContext context) throws IOException {
    }

    @Override
    public int computeSerializedSize() {
        int size = SIZE_CONSTRUCTOR_ID;
        return size;
    }

    @Override
    public String toString() {
        return _constructor;
    }

    @Override
    public int getConstructorId() {
        return CONSTRUCTOR_ID;
    }
}
