package io.objects.tl.api.request;

import static io.objects.tl.StreamUtils.*;
import static io.objects.tl.TLObjectUtils.*;

import io.objects.tl.TLContext;
import io.objects.tl.api.TLAbsInputChannel;
import io.objects.tl.api.TLAbsInputUser;
import io.objects.tl.api.TLAbsUpdates;
import io.objects.tl.api.TLChannelBannedRights;
import io.objects.tl.core.TLMethod;
import io.objects.tl.core.TLObject;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;

/**
 * This class is generated by Mono's TL class generator
 */
public class TLRequestChannelsEditBanned extends TLMethod<TLAbsUpdates> {
    public static final int CONSTRUCTOR_ID = 0xbfd915cd;

    protected TLAbsInputChannel channel;

    protected TLAbsInputUser userId;

    protected TLChannelBannedRights bannedRights;

    private final String _constructor = "channels.editBanned#bfd915cd";

    public TLRequestChannelsEditBanned() {
    }

    public TLRequestChannelsEditBanned(TLAbsInputChannel channel, TLAbsInputUser userId,
            TLChannelBannedRights bannedRights) {
        this.channel = channel;
        this.userId = userId;
        this.bannedRights = bannedRights;
    }

    @Override
    @SuppressWarnings({"unchecked", "SimplifiableConditionalExpression"})
    public TLAbsUpdates deserializeResponse(InputStream stream, TLContext context) throws
            IOException {
        final TLObject response = readTLObject(stream, context);
        if (response == null) {
            throw new IOException("Unable to parse response");
        }
        if (!(response instanceof TLAbsUpdates)) {
            throw new IOException("Incorrect response type, expected " + getClass().getCanonicalName() + ", found " + response.getClass().getCanonicalName());
        }
        return (TLAbsUpdates) response;
    }

    @Override
    public void serializeBody(OutputStream stream) throws IOException {
        writeTLObject(channel, stream);
        writeTLObject(userId, stream);
        writeTLObject(bannedRights, stream);
    }

    @Override
    @SuppressWarnings({"unchecked", "SimplifiableConditionalExpression"})
    public void deserializeBody(InputStream stream, TLContext context) throws IOException {
        channel = readTLObject(stream, context, TLAbsInputChannel.class, -1);
        userId = readTLObject(stream, context, TLAbsInputUser.class, -1);
        bannedRights = readTLObject(stream, context, TLChannelBannedRights.class, TLChannelBannedRights.CONSTRUCTOR_ID);
    }

    @Override
    public int computeSerializedSize() {
        int size = SIZE_CONSTRUCTOR_ID;
        size += channel.computeSerializedSize();
        size += userId.computeSerializedSize();
        size += bannedRights.computeSerializedSize();
        return size;
    }

    @Override
    public String toString() {
        return _constructor;
    }

    @Override
    public int getConstructorId() {
        return CONSTRUCTOR_ID;
    }

    public TLAbsInputChannel getChannel() {
        return channel;
    }

    public void setChannel(TLAbsInputChannel channel) {
        this.channel = channel;
    }

    public TLAbsInputUser getUserId() {
        return userId;
    }

    public void setUserId(TLAbsInputUser userId) {
        this.userId = userId;
    }

    public TLChannelBannedRights getBannedRights() {
        return bannedRights;
    }

    public void setBannedRights(TLChannelBannedRights bannedRights) {
        this.bannedRights = bannedRights;
    }
}
