package io.objects.tl.api.request;

import static io.objects.tl.StreamUtils.*;
import static io.objects.tl.TLObjectUtils.*;

import io.objects.tl.TLContext;
import io.objects.tl.api.TLMessageRange;
import io.objects.tl.core.TLMethod;
import io.objects.tl.core.TLObject;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;

/**
 * This class is generated by Mono's TL class generator
 */
public class TLRequestInvokeWithMessagesRange<T extends TLObject> extends TLMethod<T> {
    public static final int CONSTRUCTOR_ID = 0x365275f2;

    protected TLMessageRange range;

    protected TLMethod<T> query;

    private final String _constructor = "invokeWithMessagesRange#365275f2";

    public TLRequestInvokeWithMessagesRange() {
    }

    public TLRequestInvokeWithMessagesRange(TLMessageRange range, TLMethod<T> query) {
        this.range = range;
        this.query = query;
    }

    @Override
    @SuppressWarnings({"unchecked", "SimplifiableConditionalExpression"})
    public T deserializeResponse(InputStream stream, TLContext context) throws IOException {
        return query.deserializeResponse(stream, context);
    }

    @Override
    public void serializeBody(OutputStream stream) throws IOException {
        writeTLObject(range, stream);
        writeTLMethod(query, stream);
    }

    @Override
    @SuppressWarnings({"unchecked", "SimplifiableConditionalExpression"})
    public void deserializeBody(InputStream stream, TLContext context) throws IOException {
        range = readTLObject(stream, context, TLMessageRange.class, TLMessageRange.CONSTRUCTOR_ID);
        query = readTLMethod(stream, context);
    }

    @Override
    public int computeSerializedSize() {
        int size = SIZE_CONSTRUCTOR_ID;
        size += range.computeSerializedSize();
        size += query.computeSerializedSize();
        return size;
    }

    @Override
    public String toString() {
        return _constructor;
    }

    @Override
    public int getConstructorId() {
        return CONSTRUCTOR_ID;
    }

    public TLMessageRange getRange() {
        return range;
    }

    public void setRange(TLMessageRange range) {
        this.range = range;
    }

    public TLMethod<T> getQuery() {
        return query;
    }

    public void setQuery(TLMethod<T> query) {
        this.query = query;
    }
}
