package io.tlobjects.tl.api.messages;

import static io.tlobjects.tl.StreamUtils.*;
import static io.tlobjects.tl.TLObjectUtils.*;

import io.tlobjects.tl.core.TLBytes;
import io.tlobjects.tl.core.TLObject;

/**
 * Abstraction level for the following constructors:
 * <ul>
 * <li>{@link TLDhConfig}: messages.dhConfig#2c221edd</li>
 * <li>{@link TLDhConfigNotModified}: messages.dhConfigNotModified#c0e24635</li>
 * </ul>
 *
 * This class is generated by Mono's TL class generator
 */
public abstract class TLAbsDhConfig extends TLObject {
    protected TLBytes random;

    public TLAbsDhConfig() {
    }

    public TLBytes getRandom() {
        return random;
    }

    public void setRandom(TLBytes random) {
        this.random = random;
    }
}
