package io.tlobjects.tl.api.messages;

import static io.tlobjects.tl.StreamUtils.*;
import static io.tlobjects.tl.TLObjectUtils.*;

import io.tlobjects.tl.core.TLObject;

/**
 * Abstraction level for the following constructors:
 * <ul>
 * <li>{@link TLFeaturedStickers}: messages.featuredStickers#f89d88e5</li>
 * <li>{@link TLFeaturedStickersNotModified}: messages.featuredStickersNotModified#4ede3cf</li>
 * </ul>
 *
 * This class is generated by Mono's TL class generator
 */
public abstract class TLAbsFeaturedStickers extends TLObject {
    public TLAbsFeaturedStickers() {
    }
}
