package io.tlobjects.tl.api.messages;

import static io.tlobjects.tl.StreamUtils.*;
import static io.tlobjects.tl.TLObjectUtils.*;

import io.tlobjects.tl.core.TLObject;

/**
 * Abstraction level for the following constructors:
 * <ul>
 * <li>{@link TLFoundStickerSets}: messages.foundStickerSets#5108d648</li>
 * <li>{@link TLFoundStickerSetsNotModified}: messages.foundStickerSetsNotModified#d54b65d</li>
 * </ul>
 *
 * This class is generated by Mono's TL class generator
 */
public abstract class TLAbsFoundStickerSets extends TLObject {
    public TLAbsFoundStickerSets() {
    }
}
