package io.objects.tl.api.help;

import static io.objects.tl.StreamUtils.*;
import static io.objects.tl.TLObjectUtils.*;

import io.objects.tl.core.TLObject;

/**
 * Abstraction level for the following constructors:
 * <ul>
 * <li>{@link TLAppUpdate}: help.appUpdate#1da7158f</li>
 * <li>{@link TLNoAppUpdate}: help.noAppUpdate#c45a6536</li>
 * </ul>
 *
 * This class is generated by Mono's TL class generator
 */
public abstract class TLAbsAppUpdate extends TLObject {
    public TLAbsAppUpdate() {
    }
}
