package io.objects.tl.api.help;

import static io.objects.tl.StreamUtils.*;
import static io.objects.tl.TLObjectUtils.*;

import io.objects.tl.core.TLObject;

/**
 * Abstraction level for the following constructors:
 * <ul>
 * <li>{@link TLPassportConfig}: help.passportConfig#a098d6af</li>
 * <li>{@link TLPassportConfigNotModified}: help.passportConfigNotModified#bfb9f457</li>
 * </ul>
 *
 * This class is generated by Mono's TL class generator
 */
public abstract class TLAbsPassportConfig extends TLObject {
    public TLAbsPassportConfig() {
    }
}
