package io.objects.tl.api;

import static io.objects.tl.StreamUtils.*;
import static io.objects.tl.TLObjectUtils.*;

import io.objects.tl.api.account.TLAuthorizationForm;
import io.objects.tl.api.account.TLAuthorizations;
import io.objects.tl.api.account.TLPassword;
import io.objects.tl.api.account.TLPasswordInputSettings;
import io.objects.tl.api.account.TLPasswordSettings;
import io.objects.tl.api.account.TLPrivacyRules;
import io.objects.tl.api.account.TLSentEmailCode;
import io.objects.tl.api.account.TLTakeout;
import io.objects.tl.api.account.TLTmpPassword;
import io.objects.tl.api.account.TLWebAuthorizations;
import io.objects.tl.api.auth.TLAuthorization;
import io.objects.tl.api.auth.TLExportedAuthorization;
import io.objects.tl.api.auth.TLPasswordRecovery;
import io.objects.tl.api.auth.TLSentCode;
import io.objects.tl.api.channels.TLAbsChannelParticipants;
import io.objects.tl.api.channels.TLAdminLogResults;
import io.objects.tl.api.channels.TLChannelParticipant;
import io.objects.tl.api.contacts.TLAbsBlocked;
import io.objects.tl.api.contacts.TLAbsContacts;
import io.objects.tl.api.contacts.TLAbsTopPeers;
import io.objects.tl.api.contacts.TLFound;
import io.objects.tl.api.contacts.TLImportedContacts;
import io.objects.tl.api.contacts.TLLink;
import io.objects.tl.api.contacts.TLResolvedPeer;
import io.objects.tl.api.help.TLAbsAppUpdate;
import io.objects.tl.api.help.TLAbsDeepLinkInfo;
import io.objects.tl.api.help.TLAbsPassportConfig;
import io.objects.tl.api.help.TLAbsProxyData;
import io.objects.tl.api.help.TLAbsTermsOfServiceUpdate;
import io.objects.tl.api.help.TLInviteText;
import io.objects.tl.api.help.TLRecentMeUrls;
import io.objects.tl.api.help.TLSupport;
import io.objects.tl.api.messages.TLAbsAllStickers;
import io.objects.tl.api.messages.TLAbsChats;
import io.objects.tl.api.messages.TLAbsDhConfig;
import io.objects.tl.api.messages.TLAbsDialogs;
import io.objects.tl.api.messages.TLAbsFavedStickers;
import io.objects.tl.api.messages.TLAbsFeaturedStickers;
import io.objects.tl.api.messages.TLAbsFoundStickerSets;
import io.objects.tl.api.messages.TLAbsMessages;
import io.objects.tl.api.messages.TLAbsRecentStickers;
import io.objects.tl.api.messages.TLAbsSavedGifs;
import io.objects.tl.api.messages.TLAbsSentEncryptedMessage;
import io.objects.tl.api.messages.TLAbsStickerSetInstallResult;
import io.objects.tl.api.messages.TLAbsStickers;
import io.objects.tl.api.messages.TLAffectedHistory;
import io.objects.tl.api.messages.TLAffectedMessages;
import io.objects.tl.api.messages.TLArchivedStickers;
import io.objects.tl.api.messages.TLBotCallbackAnswer;
import io.objects.tl.api.messages.TLBotResults;
import io.objects.tl.api.messages.TLChatFull;
import io.objects.tl.api.messages.TLFoundGifs;
import io.objects.tl.api.messages.TLHighScores;
import io.objects.tl.api.messages.TLMessageEditData;
import io.objects.tl.api.messages.TLPeerDialogs;
import io.objects.tl.api.messages.TLStickerSet;
import io.objects.tl.api.monobot.TLBotFile;
import io.objects.tl.api.payments.TLAbsPaymentResult;
import io.objects.tl.api.payments.TLPaymentForm;
import io.objects.tl.api.payments.TLPaymentReceipt;
import io.objects.tl.api.payments.TLSavedInfo;
import io.objects.tl.api.payments.TLValidatedRequestedInfo;
import io.objects.tl.api.phone.TLPhoneCall;
import io.objects.tl.api.photos.TLAbsPhotos;
import io.objects.tl.api.photos.TLPhoto;
import io.objects.tl.api.updates.TLAbsChannelDifference;
import io.objects.tl.api.updates.TLAbsDifference;
import io.objects.tl.api.updates.TLState;
import io.objects.tl.api.upload.TLAbsCdnFile;
import io.objects.tl.api.upload.TLAbsFile;
import io.objects.tl.api.upload.TLWebFile;
import io.objects.tl.core.TLBool;
import io.objects.tl.core.TLBytes;
import io.objects.tl.core.TLIntVector;
import io.objects.tl.core.TLLongVector;
import io.objects.tl.core.TLMethod;
import io.objects.tl.core.TLObject;
import io.objects.tl.core.TLStringVector;
import io.objects.tl.core.TLVector;
import io.objects.tl.exception.RpcErrorException;
import java.io.IOException;
import java.lang.Integer;
import java.lang.String;
import java.lang.SuppressWarnings;

/**
 * This class is generated by Mono's TL class generator
 */
@SuppressWarnings({"unused", "unchecked", "RedundantCast"})
public interface TelegramApi {
    TLBool accountAcceptAuthorization(int botId, String scope, String publicKey,
            TLVector<TLSecureValueHash> valueHashes, TLSecureCredentialsEncrypted credentials)
            throws RpcErrorException, IOException;

    TLAbsUser accountChangePhone(String phoneNumber, String phoneCodeHash, String phoneCode) throws
            RpcErrorException, IOException;

    TLBool accountCheckUsername(String username) throws RpcErrorException, IOException;

    TLBool accountConfirmPhone(String phoneCodeHash, String phoneCode) throws RpcErrorException,
            IOException;

    TLBool accountDeleteAccount(String reason) throws RpcErrorException, IOException;

    TLBool accountDeleteSecureValue(TLVector<TLAbsSecureValueType> types) throws RpcErrorException,
            IOException;

    TLBool accountFinishTakeoutSession(boolean success) throws RpcErrorException, IOException;

    TLAccountDaysTTL accountGetAccountTTL() throws RpcErrorException, IOException;

    TLVector<TLSecureValue> accountGetAllSecureValues() throws RpcErrorException, IOException;

    TLAuthorizationForm accountGetAuthorizationForm(int botId, String scope, String publicKey)
            throws RpcErrorException, IOException;

    TLAuthorizations accountGetAuthorizations() throws RpcErrorException, IOException;

    TLPeerNotifySettings accountGetNotifySettings(TLAbsInputNotifyPeer peer) throws
            RpcErrorException, IOException;

    TLPassword accountGetPassword() throws RpcErrorException, IOException;

    TLPasswordSettings accountGetPasswordSettings(TLAbsInputCheckPasswordSRP password) throws
            RpcErrorException, IOException;

    TLPrivacyRules accountGetPrivacy(TLAbsInputPrivacyKey key) throws RpcErrorException,
            IOException;

    TLVector<TLSecureValue> accountGetSecureValue(TLVector<TLAbsSecureValueType> types) throws
            RpcErrorException, IOException;

    TLTmpPassword accountGetTmpPassword(TLAbsInputCheckPasswordSRP password, int period) throws
            RpcErrorException, IOException;

    TLVector<TLAbsWallPaper> accountGetWallPapers() throws RpcErrorException, IOException;

    TLWebAuthorizations accountGetWebAuthorizations() throws RpcErrorException, IOException;

    TLTakeout accountInitTakeoutSession(boolean contacts, boolean messageUsers,
            boolean messageChats, boolean messageMegagroups, boolean messageChannels, boolean files,
            Integer fileMaxSize) throws RpcErrorException, IOException;

    TLBool accountRegisterDevice(int tokenType, String token, boolean appSandbox, TLBytes secret,
            TLIntVector otherUids) throws RpcErrorException, IOException;

    TLBool accountRegisterDeviceV71(int tokenType, String token) throws RpcErrorException,
            IOException;

    TLBool accountReportPeer(TLAbsInputPeer peer, TLAbsReportReason reason) throws
            RpcErrorException, IOException;

    TLBool accountResetAuthorization(long hash) throws RpcErrorException, IOException;

    TLBool accountResetNotifySettings() throws RpcErrorException, IOException;

    TLBool accountResetWebAuthorization(long hash) throws RpcErrorException, IOException;

    TLBool accountResetWebAuthorizations() throws RpcErrorException, IOException;

    TLSecureValue accountSaveSecureValue(TLInputSecureValue value, long secureSecretId) throws
            RpcErrorException, IOException;

    TLSentCode accountSendChangePhoneCode(boolean allowFlashcall, String phoneNumber,
            boolean currentNumber) throws RpcErrorException, IOException;

    TLSentCode accountSendConfirmPhoneCode(boolean allowFlashcall, String hash,
            boolean currentNumber) throws RpcErrorException, IOException;

    TLSentEmailCode accountSendVerifyEmailCode(String email) throws RpcErrorException, IOException;

    TLSentCode accountSendVerifyPhoneCode(boolean allowFlashcall, String phoneNumber,
            boolean currentNumber) throws RpcErrorException, IOException;

    TLBool accountSetAccountTTL(TLAccountDaysTTL ttl) throws RpcErrorException, IOException;

    TLPrivacyRules accountSetPrivacy(TLAbsInputPrivacyKey key,
            TLVector<TLAbsInputPrivacyRule> rules) throws RpcErrorException, IOException;

    TLBool accountUnregisterDevice(int tokenType, String token, TLIntVector otherUids) throws
            RpcErrorException, IOException;

    TLBool accountUpdateDeviceLocked(int period) throws RpcErrorException, IOException;

    TLBool accountUpdateNotifySettings(TLAbsInputNotifyPeer peer,
            TLInputPeerNotifySettings settings) throws RpcErrorException, IOException;

    TLBool accountUpdatePasswordSettings(TLAbsInputCheckPasswordSRP password,
            TLPasswordInputSettings newSettings) throws RpcErrorException, IOException;

    TLAbsUser accountUpdateProfile(String firstName, String lastName, String about) throws
            RpcErrorException, IOException;

    TLBool accountUpdateStatus(boolean offline) throws RpcErrorException, IOException;

    TLAbsUser accountUpdateUsername(String username) throws RpcErrorException, IOException;

    TLBool accountVerifyEmail(String email, String code) throws RpcErrorException, IOException;

    TLBool accountVerifyPhone(String phoneNumber, String phoneCodeHash, String phoneCode) throws
            RpcErrorException, IOException;

    TLBool authBindTempAuthKey(long permAuthKeyId, long nonce, int expiresAt,
            TLBytes encryptedMessage) throws RpcErrorException, IOException;

    TLBool authCancelCode(String phoneNumber, String phoneCodeHash) throws RpcErrorException,
            IOException;

    TLAuthorization authCheckPassword(TLAbsInputCheckPasswordSRP password) throws RpcErrorException,
            IOException;

    TLBool authDropTempAuthKeys(TLLongVector exceptAuthKeys) throws RpcErrorException, IOException;

    TLExportedAuthorization authExportAuthorization(int dcId) throws RpcErrorException, IOException;

    TLAuthorization authImportAuthorization(int id, TLBytes bytes) throws RpcErrorException,
            IOException;

    TLAuthorization authImportBotAuthorization(int flags, int apiId, String apiHash,
            String botAuthToken) throws RpcErrorException, IOException;

    TLBool authLogOut() throws RpcErrorException, IOException;

    TLAuthorization authRecoverPassword(String code) throws RpcErrorException, IOException;

    TLPasswordRecovery authRequestPasswordRecovery() throws RpcErrorException, IOException;

    TLSentCode authResendCode(String phoneNumber, String phoneCodeHash) throws RpcErrorException,
            IOException;

    TLBool authResetAuthorizations() throws RpcErrorException, IOException;

    TLSentCode authSendCode(boolean allowFlashcall, String phoneNumber, boolean currentNumber,
            int apiId, String apiHash) throws RpcErrorException, IOException;

    TLAuthorization authSignIn(String phoneNumber, String phoneCodeHash, String phoneCode) throws
            RpcErrorException, IOException;

    TLAuthorization authSignUp(String phoneNumber, String phoneCodeHash, String phoneCode,
            String firstName, String lastName) throws RpcErrorException, IOException;

    TLBool botsAnswerWebhookJSONQuery(long queryId, TLDataJSON data) throws RpcErrorException,
            IOException;

    TLDataJSON botsSendCustomRequest(String customMethod, TLDataJSON params) throws
            RpcErrorException, IOException;

    TLAbsMessages channelGetMessagesV71(TLAbsInputChannel channel, TLIntVector id) throws
            RpcErrorException, IOException;

    TLBool channelsCheckUsername(TLAbsInputChannel channel, String username) throws
            RpcErrorException, IOException;

    TLAbsUpdates channelsCreateChannel(boolean broadcast, boolean megagroup, String title,
            String about) throws RpcErrorException, IOException;

    TLAbsUpdates channelsDeleteChannel(TLAbsInputChannel channel) throws RpcErrorException,
            IOException;

    TLBool channelsDeleteHistory(TLAbsInputChannel channel, int maxId) throws RpcErrorException,
            IOException;

    TLAffectedMessages channelsDeleteMessages(TLAbsInputChannel channel, TLIntVector id) throws
            RpcErrorException, IOException;

    TLAffectedHistory channelsDeleteUserHistory(TLAbsInputChannel channel, TLAbsInputUser userId)
            throws RpcErrorException, IOException;

    TLBool channelsEditAbout(TLAbsInputChannel channel, String about) throws RpcErrorException,
            IOException;

    TLAbsUpdates channelsEditAdmin(TLAbsInputChannel channel, TLAbsInputUser userId,
            TLChannelAdminRights adminRights) throws RpcErrorException, IOException;

    TLAbsUpdates channelsEditBanned(TLAbsInputChannel channel, TLAbsInputUser userId,
            TLChannelBannedRights bannedRights) throws RpcErrorException, IOException;

    TLAbsUpdates channelsEditPhoto(TLAbsInputChannel channel, TLAbsInputChatPhoto photo) throws
            RpcErrorException, IOException;

    TLAbsUpdates channelsEditTitle(TLAbsInputChannel channel, String title) throws
            RpcErrorException, IOException;

    TLAbsExportedChatInvite channelsExportInvite(TLAbsInputChannel channel) throws
            RpcErrorException, IOException;

    TLExportedMessageLink channelsExportMessageLink(TLAbsInputChannel channel, int id,
            boolean grouped) throws RpcErrorException, IOException;

    TLAdminLogResults channelsGetAdminLog(TLAbsInputChannel channel, String q,
            TLChannelAdminLogEventsFilter eventsFilter, TLVector<TLAbsInputUser> admins, long maxId,
            long minId, int limit) throws RpcErrorException, IOException;

    TLAbsChats channelsGetAdminedPublicChannels() throws RpcErrorException, IOException;

    TLAbsChats channelsGetChannels(TLVector<TLAbsInputChannel> id) throws RpcErrorException,
            IOException;

    TLChatFull channelsGetFullChannel(TLAbsInputChannel channel) throws RpcErrorException,
            IOException;

    TLAbsChats channelsGetLeftChannels(int offset) throws RpcErrorException, IOException;

    TLAbsMessages channelsGetMessages(TLAbsInputChannel channel, TLVector<TLAbsInputMessage> id)
            throws RpcErrorException, IOException;

    TLChannelParticipant channelsGetParticipant(TLAbsInputChannel channel, TLAbsInputUser userId)
            throws RpcErrorException, IOException;

    TLAbsChannelParticipants channelsGetParticipants(TLAbsInputChannel channel,
            TLAbsChannelParticipantsFilter filter, int offset, int limit, int hash) throws
            RpcErrorException, IOException;

    TLAbsUpdates channelsInviteToChannel(TLAbsInputChannel channel, TLVector<TLAbsInputUser> users)
            throws RpcErrorException, IOException;

    TLAbsUpdates channelsJoinChannel(TLAbsInputChannel channel) throws RpcErrorException,
            IOException;

    TLAbsUpdates channelsLeaveChannel(TLAbsInputChannel channel) throws RpcErrorException,
            IOException;

    TLBool channelsReadHistory(TLAbsInputChannel channel, int maxId) throws RpcErrorException,
            IOException;

    TLBool channelsReadMessageContents(TLAbsInputChannel channel, TLIntVector id) throws
            RpcErrorException, IOException;

    TLBool channelsReportSpam(TLAbsInputChannel channel, TLAbsInputUser userId, TLIntVector id)
            throws RpcErrorException, IOException;

    TLBool channelsSetStickers(TLAbsInputChannel channel, TLAbsInputStickerSet stickerset) throws
            RpcErrorException, IOException;

    TLAbsUpdates channelsToggleInvites(TLAbsInputChannel channel, boolean enabled) throws
            RpcErrorException, IOException;

    TLAbsUpdates channelsTogglePreHistoryHidden(TLAbsInputChannel channel, boolean enabled) throws
            RpcErrorException, IOException;

    TLAbsUpdates channelsToggleSignatures(TLAbsInputChannel channel, boolean enabled) throws
            RpcErrorException, IOException;

    TLAbsUpdates channelsUpdatePinnedMessage(boolean silent, TLAbsInputChannel channel, int id)
            throws RpcErrorException, IOException;

    TLBool channelsUpdateUsername(TLAbsInputChannel channel, String username) throws
            RpcErrorException, IOException;

    TLBool contactsBlock(TLAbsInputUser id) throws RpcErrorException, IOException;

    TLLink contactsDeleteContact(TLAbsInputUser id) throws RpcErrorException, IOException;

    TLBool contactsDeleteContacts(TLVector<TLAbsInputUser> id) throws RpcErrorException,
            IOException;

    TLIntVector contactsExportCard() throws RpcErrorException, IOException;

    TLAbsBlocked contactsGetBlocked(int offset, int limit) throws RpcErrorException, IOException;

    TLAbsContacts contactsGetContacts(int hash) throws RpcErrorException, IOException;

    TLVector<TLSavedPhoneContact> contactsGetSaved() throws RpcErrorException, IOException;

    TLVector<TLContactStatus> contactsGetStatuses() throws RpcErrorException, IOException;

    TLAbsTopPeers contactsGetTopPeers(boolean correspondents, boolean botsPm, boolean botsInline,
            boolean phoneCalls, boolean groups, boolean channels, int offset, int limit, int hash)
            throws RpcErrorException, IOException;

    TLAbsUser contactsImportCard(TLIntVector exportCard) throws RpcErrorException, IOException;

    TLImportedContacts contactsImportContacts(TLVector<TLInputPhoneContact> contacts) throws
            RpcErrorException, IOException;

    TLBool contactsResetSaved() throws RpcErrorException, IOException;

    TLBool contactsResetTopPeerRating(TLAbsTopPeerCategory category, TLAbsInputPeer peer) throws
            RpcErrorException, IOException;

    TLResolvedPeer contactsResolveUsername(String username) throws RpcErrorException, IOException;

    TLFound contactsSearch(String q, int limit) throws RpcErrorException, IOException;

    TLBool contactsToggleTopPeers(boolean enabled) throws RpcErrorException, IOException;

    TLBool contactsUnblock(TLAbsInputUser id) throws RpcErrorException, IOException;

    TLLangPackLanguage getLanguages() throws RpcErrorException, IOException;

    TLBool helpAcceptTermsOfService(TLDataJSON id) throws RpcErrorException, IOException;

    TLAbsUpdates helpGetAppChangelog(String prevAppVersion) throws RpcErrorException, IOException;

    TLAbsAppUpdate helpGetAppUpdate(String source) throws RpcErrorException, IOException;

    TLCdnConfig helpGetCdnConfig() throws RpcErrorException, IOException;

    TLConfig helpGetConfig() throws RpcErrorException, IOException;

    TLAbsDeepLinkInfo helpGetDeepLinkInfo(String path) throws RpcErrorException, IOException;

    TLInviteText helpGetInviteText() throws RpcErrorException, IOException;

    TLNearestDc helpGetNearestDc() throws RpcErrorException, IOException;

    TLAbsPassportConfig helpGetPassportConfig(int hash) throws RpcErrorException, IOException;

    TLAbsProxyData helpGetProxyData() throws RpcErrorException, IOException;

    TLRecentMeUrls helpGetRecentMeUrls(String referer) throws RpcErrorException, IOException;

    TLSupport helpGetSupport() throws RpcErrorException, IOException;

    TLAbsTermsOfServiceUpdate helpGetTermsOfServiceUpdate() throws RpcErrorException, IOException;

    TLBool helpSaveAppLog(TLVector<TLInputAppEvent> events) throws RpcErrorException, IOException;

    TLBool helpSetBotUpdatesStatus(int pendingUpdatesCount, String message) throws
            RpcErrorException, IOException;

    <T extends TLObject> T initConnection(int apiId, String deviceModel, String systemVersion,
            String appVersion, String systemLangCode, String langPack, String langCode,
            TLInputClientProxy proxy, TLMethod<T> query) throws RpcErrorException, IOException;

    <T extends TLObject> T invokeAfterMsg(long msgId, TLMethod<T> query) throws RpcErrorException,
            IOException;

    <T extends TLObject> T invokeAfterMsgs(TLLongVector msgIds, TLMethod<T> query) throws
            RpcErrorException, IOException;

    <T extends TLObject> T invokeWithLayer(int layer, TLMethod<T> query) throws RpcErrorException,
            IOException;

    <T extends TLObject> T invokeWithMessagesRange(TLMessageRange range, TLMethod<T> query) throws
            RpcErrorException, IOException;

    <T extends TLObject> T invokeWithTakeout(long takeoutId, TLMethod<T> query) throws
            RpcErrorException, IOException;

    <T extends TLObject> T invokeWithoutUpdates(TLMethod<T> query) throws RpcErrorException,
            IOException;

    TLLangPackDifference langpackGetDifference(int fromVersion) throws RpcErrorException,
            IOException;

    TLLangPackDifference langpackGetLangPack(String langPack, String langCode) throws
            RpcErrorException, IOException;

    TLVector<TLLangPackLanguage> langpackGetLanguages(String langPack) throws RpcErrorException,
            IOException;

    TLVector<TLAbsLangPackString> langpackGetStrings(String langPack, String langCode,
            TLStringVector keys) throws RpcErrorException, IOException;

    TLAbsEncryptedChat messagesAcceptEncryption(TLInputEncryptedChat peer, TLBytes gB,
            long keyFingerprint) throws RpcErrorException, IOException;

    TLAbsUpdates messagesAddChatUser(int chatId, TLAbsInputUser userId, int fwdLimit) throws
            RpcErrorException, IOException;

    TLAbsChatInvite messagesCheckChatInvite(String hash) throws RpcErrorException, IOException;

    TLBool messagesClearAllDrafts() throws RpcErrorException, IOException;

    TLBool messagesClearRecentStickers(boolean attached) throws RpcErrorException, IOException;

    TLAbsUpdates messagesCreateChat(TLVector<TLAbsInputUser> users, String title) throws
            RpcErrorException, IOException;

    TLAbsUpdates messagesDeleteChatUser(int chatId, TLAbsInputUser userId) throws RpcErrorException,
            IOException;

    TLAffectedHistory messagesDeleteHistory(boolean justClear, TLAbsInputPeer peer, int maxId)
            throws RpcErrorException, IOException;

    TLAffectedMessages messagesDeleteMessages(boolean revoke, TLIntVector id) throws
            RpcErrorException, IOException;

    TLBool messagesDiscardEncryption(int chatId) throws RpcErrorException, IOException;

    TLBool messagesEditChatAdmin(int chatId, TLAbsInputUser userId, boolean isAdmin) throws
            RpcErrorException, IOException;

    TLAbsUpdates messagesEditChatPhoto(int chatId, TLAbsInputChatPhoto photo) throws
            RpcErrorException, IOException;

    TLAbsUpdates messagesEditChatTitle(int chatId, String title) throws RpcErrorException,
            IOException;

    TLBool messagesEditInlineBotMessage(boolean noWebpage, boolean stopGeoLive,
            TLInputBotInlineMessageID id, String message, TLAbsInputMedia media,
            TLAbsReplyMarkup replyMarkup, TLVector<TLAbsMessageEntity> entities,
            TLAbsInputGeoPoint geoPoint) throws RpcErrorException, IOException;

    TLAbsUpdates messagesEditMessage(boolean noWebpage, boolean stopGeoLive, TLAbsInputPeer peer,
            int id, String message, TLAbsInputMedia media, TLAbsReplyMarkup replyMarkup,
            TLVector<TLAbsMessageEntity> entities, TLAbsInputGeoPoint geoPoint) throws
            RpcErrorException, IOException;

    TLAbsExportedChatInvite messagesExportChatInvite(int chatId) throws RpcErrorException,
            IOException;

    TLBool messagesFaveSticker(TLAbsInputDocument id, boolean unfave) throws RpcErrorException,
            IOException;

    TLAbsUpdates messagesForwardMessages(boolean silent, boolean background, boolean withMyScore,
            boolean grouped, TLAbsInputPeer fromPeer, TLIntVector id, TLLongVector randomId,
            TLAbsInputPeer toPeer) throws RpcErrorException, IOException;

    TLAbsChats messagesGetAllChats(TLIntVector exceptIds) throws RpcErrorException, IOException;

    TLAbsUpdates messagesGetAllDrafts() throws RpcErrorException, IOException;

    TLAbsAllStickers messagesGetAllStickers(int hash) throws RpcErrorException, IOException;

    TLArchivedStickers messagesGetArchivedStickers(boolean masks, long offsetId, int limit) throws
            RpcErrorException, IOException;

    TLVector<TLAbsStickerSetCovered> messagesGetAttachedStickers(TLAbsInputStickeredMedia media)
            throws RpcErrorException, IOException;

    TLBotCallbackAnswer messagesGetBotCallbackAnswer(boolean game, TLAbsInputPeer peer, int msgId,
            TLBytes data) throws RpcErrorException, IOException;

    TLAbsChats messagesGetChats(TLIntVector id) throws RpcErrorException, IOException;

    TLAbsChats messagesGetCommonChats(TLAbsInputUser userId, int maxId, int limit) throws
            RpcErrorException, IOException;

    TLAbsDhConfig messagesGetDhConfig(int version, int randomLength) throws RpcErrorException,
            IOException;

    TLVector<TLDialogPeer> messagesGetDialogUnreadMarks() throws RpcErrorException, IOException;

    TLAbsDialogs messagesGetDialogs(boolean excludePinned, int offsetDate, int offsetId,
            TLAbsInputPeer offsetPeer, int limit, int hash) throws RpcErrorException, IOException;

    TLAbsDocument messagesGetDocumentByHash(TLBytes sha256, int size, String mimeType) throws
            RpcErrorException, IOException;

    TLAbsFavedStickers messagesGetFavedStickers(int hash) throws RpcErrorException, IOException;

    TLAbsFeaturedStickers messagesGetFeaturedStickers(int hash) throws RpcErrorException,
            IOException;

    TLChatFull messagesGetFullChat(int chatId) throws RpcErrorException, IOException;

    TLHighScores messagesGetGameHighScores(TLAbsInputPeer peer, int id, TLAbsInputUser userId)
            throws RpcErrorException, IOException;

    TLAbsMessages messagesGetHistory(TLAbsInputPeer peer, int offsetId, int offsetDate,
            int addOffset, int limit, int maxId, int minId, int hash) throws RpcErrorException,
            IOException;

    TLAbsMessages messagesGetHistoryV71(TLAbsInputPeer peer, int offsetId, int offsetDate,
            int addOffset, int limit, int maxId, int minId) throws RpcErrorException, IOException;

    TLBotResults messagesGetInlineBotResults(TLAbsInputUser bot, TLAbsInputPeer peer,
            TLAbsInputGeoPoint geoPoint, String query, String offset) throws RpcErrorException,
            IOException;

    TLHighScores messagesGetInlineGameHighScores(TLInputBotInlineMessageID id,
            TLAbsInputUser userId) throws RpcErrorException, IOException;

    TLAbsAllStickers messagesGetMaskStickers(int hash) throws RpcErrorException, IOException;

    TLMessageEditData messagesGetMessageEditData(TLAbsInputPeer peer, int id) throws
            RpcErrorException, IOException;

    TLAbsMessages messagesGetMessages(TLVector<TLAbsInputMessage> id) throws RpcErrorException,
            IOException;

    TLAbsMessages messagesGetMessagesV71(TLIntVector id) throws RpcErrorException, IOException;

    TLIntVector messagesGetMessagesViews(TLAbsInputPeer peer, TLIntVector id, boolean increment)
            throws RpcErrorException, IOException;

    TLPeerDialogs messagesGetPeerDialogs(TLVector<TLInputDialogPeer> peers) throws
            RpcErrorException, IOException;

    TLPeerSettings messagesGetPeerSettings(TLAbsInputPeer peer) throws RpcErrorException,
            IOException;

    TLPeerDialogs messagesGetPinnedDialogs() throws RpcErrorException, IOException;

    TLAbsMessages messagesGetRecentLocations(TLAbsInputPeer peer, int limit, int hash) throws
            RpcErrorException, IOException;

    TLAbsRecentStickers messagesGetRecentStickers(boolean attached, int hash) throws
            RpcErrorException, IOException;

    TLAbsSavedGifs messagesGetSavedGifs(int hash) throws RpcErrorException, IOException;

    TLVector<TLMessageRange> messagesGetSplitRanges() throws RpcErrorException, IOException;

    TLStickerSet messagesGetStickerSet(TLAbsInputStickerSet stickerset) throws RpcErrorException,
            IOException;

    TLAbsStickers messagesGetStickers(String emoticon, int hash) throws RpcErrorException,
            IOException;

    TLAbsMessages messagesGetUnreadMentions(TLAbsInputPeer peer, int offsetId, int addOffset,
            int limit, int maxId, int minId) throws RpcErrorException, IOException;

    TLAbsWebPage messagesGetWebPage(String url, int hash) throws RpcErrorException, IOException;

    TLAbsMessageMedia messagesGetWebPagePreview(String message,
            TLVector<TLAbsMessageEntity> entities) throws RpcErrorException, IOException;

    TLBool messagesHideReportSpam(TLAbsInputPeer peer) throws RpcErrorException, IOException;

    TLAbsUpdates messagesImportChatInvite(String hash) throws RpcErrorException, IOException;

    TLAbsStickerSetInstallResult messagesInstallStickerSet(TLAbsInputStickerSet stickerset,
            boolean archived) throws RpcErrorException, IOException;

    TLBool messagesMarkDialogUnread(boolean unread, TLInputDialogPeer peer) throws
            RpcErrorException, IOException;

    TLAbsUpdates messagesMigrateChat(int chatId) throws RpcErrorException, IOException;

    TLBool messagesReadEncryptedHistory(TLInputEncryptedChat peer, int maxDate) throws
            RpcErrorException, IOException;

    TLBool messagesReadFeaturedStickers(TLLongVector id) throws RpcErrorException, IOException;

    TLAffectedMessages messagesReadHistory(TLAbsInputPeer peer, int maxId) throws RpcErrorException,
            IOException;

    TLAffectedHistory messagesReadMentions(TLAbsInputPeer peer) throws RpcErrorException,
            IOException;

    TLAffectedMessages messagesReadMessageContents(TLIntVector id) throws RpcErrorException,
            IOException;

    TLVector<TLReceivedNotifyMessage> messagesReceivedMessages(int maxId) throws RpcErrorException,
            IOException;

    TLLongVector messagesReceivedQueue(int maxQts) throws RpcErrorException, IOException;

    TLBool messagesReorderPinnedDialogs(boolean force, TLVector<TLInputDialogPeer> order) throws
            RpcErrorException, IOException;

    TLBool messagesReorderStickerSets(boolean masks, TLLongVector order) throws RpcErrorException,
            IOException;

    TLBool messagesReport(TLAbsInputPeer peer, TLIntVector id, TLAbsReportReason reason) throws
            RpcErrorException, IOException;

    TLBool messagesReportEncryptedSpam(TLInputEncryptedChat peer) throws RpcErrorException,
            IOException;

    TLBool messagesReportSpam(TLAbsInputPeer peer) throws RpcErrorException, IOException;

    TLAbsEncryptedChat messagesRequestEncryption(TLAbsInputUser userId, int randomId, TLBytes gA)
            throws RpcErrorException, IOException;

    TLBool messagesSaveDraft(boolean noWebpage, Integer replyToMsgId, TLAbsInputPeer peer,
            String message, TLVector<TLAbsMessageEntity> entities) throws RpcErrorException,
            IOException;

    TLBool messagesSaveGif(TLAbsInputDocument id, boolean unsave) throws RpcErrorException,
            IOException;

    TLBool messagesSaveRecentSticker(boolean attached, TLAbsInputDocument id, boolean unsave) throws
            RpcErrorException, IOException;

    TLAbsMessages messagesSearch(TLAbsInputPeer peer, String q, TLAbsInputUser fromId,
            TLAbsMessagesFilter filter, int minDate, int maxDate, int offsetId, int addOffset,
            int limit, int maxId, int minId, int hash) throws RpcErrorException, IOException;

    TLFoundGifs messagesSearchGifs(String q, int offset) throws RpcErrorException, IOException;

    TLAbsMessages messagesSearchGlobal(String q, int offsetDate, TLAbsInputPeer offsetPeer,
            int offsetId, int limit) throws RpcErrorException, IOException;

    TLAbsFoundStickerSets messagesSearchStickerSets(boolean excludeFeatured, String q, int hash)
            throws RpcErrorException, IOException;

    TLAbsSentEncryptedMessage messagesSendEncrypted(TLInputEncryptedChat peer, long randomId,
            TLBytes data) throws RpcErrorException, IOException;

    TLAbsSentEncryptedMessage messagesSendEncryptedFile(TLInputEncryptedChat peer, long randomId,
            TLBytes data, TLAbsInputEncryptedFile file) throws RpcErrorException, IOException;

    TLAbsSentEncryptedMessage messagesSendEncryptedService(TLInputEncryptedChat peer, long randomId,
            TLBytes data) throws RpcErrorException, IOException;

    TLAbsUpdates messagesSendInlineBotResult(boolean silent, boolean background, boolean clearDraft,
            TLAbsInputPeer peer, Integer replyToMsgId, long randomId, long queryId, String id)
            throws RpcErrorException, IOException;

    TLAbsUpdates messagesSendMedia(boolean silent, boolean background, boolean clearDraft,
            TLAbsInputPeer peer, Integer replyToMsgId, TLAbsInputMedia media, String message,
            long randomId, TLAbsReplyMarkup replyMarkup, TLVector<TLAbsMessageEntity> entities)
            throws RpcErrorException, IOException;

    TLAbsUpdates messagesSendMessage(boolean noWebpage, boolean silent, boolean background,
            boolean clearDraft, TLAbsInputPeer peer, Integer replyToMsgId, String message,
            long randomId, TLAbsReplyMarkup replyMarkup, TLVector<TLAbsMessageEntity> entities)
            throws RpcErrorException, IOException;

    TLAbsUpdates messagesSendMultiMedia(boolean silent, boolean background, boolean clearDraft,
            TLAbsInputPeer peer, Integer replyToMsgId, TLVector<TLInputSingleMedia> multiMedia)
            throws RpcErrorException, IOException;

    TLAbsUpdates messagesSendScreenshotNotification(TLAbsInputPeer peer, int replyToMsgId,
            long randomId) throws RpcErrorException, IOException;

    TLBool messagesSetBotCallbackAnswer(boolean alert, long queryId, String message, String url,
            int cacheTime) throws RpcErrorException, IOException;

    TLBool messagesSetBotPrecheckoutResults(boolean success, long queryId, String error) throws
            RpcErrorException, IOException;

    TLBool messagesSetBotShippingResults(long queryId, String error,
            TLVector<TLShippingOption> shippingOptions) throws RpcErrorException, IOException;

    TLBool messagesSetEncryptedTyping(TLInputEncryptedChat peer, boolean typing) throws
            RpcErrorException, IOException;

    TLAbsUpdates messagesSetGameScore(boolean editMessage, boolean force, TLAbsInputPeer peer,
            int id, TLAbsInputUser userId, int score) throws RpcErrorException, IOException;

    TLBool messagesSetInlineBotResults(boolean gallery, boolean _private, long queryId,
            TLVector<TLAbsInputBotInlineResult> results, int cacheTime, String nextOffset,
            TLInlineBotSwitchPM switchPm) throws RpcErrorException, IOException;

    TLBool messagesSetInlineGameScore(boolean editMessage, boolean force,
            TLInputBotInlineMessageID id, TLAbsInputUser userId, int score) throws
            RpcErrorException, IOException;

    TLBool messagesSetTyping(TLAbsInputPeer peer, TLAbsSendMessageAction action) throws
            RpcErrorException, IOException;

    TLAbsUpdates messagesStartBot(TLAbsInputUser bot, TLAbsInputPeer peer, long randomId,
            String startParam) throws RpcErrorException, IOException;

    TLAbsUpdates messagesToggleChatAdmins(int chatId, boolean enabled) throws RpcErrorException,
            IOException;

    TLBool messagesToggleDialogPin(boolean pinned, TLInputDialogPeer peer) throws RpcErrorException,
            IOException;

    TLBool messagesUninstallStickerSet(TLAbsInputStickerSet stickerset) throws RpcErrorException,
            IOException;

    TLAbsEncryptedFile messagesUploadEncryptedFile(TLInputEncryptedChat peer,
            TLAbsInputEncryptedFile file) throws RpcErrorException, IOException;

    TLAbsMessageMedia messagesUploadMedia(TLAbsInputPeer peer, TLAbsInputMedia media) throws
            RpcErrorException, IOException;

    TLAbsBotUserProfilePhoto monobotBotUpdateProfilePhoto(TLAbsInputPhoto id, long requestId,
            int botId) throws RpcErrorException, IOException;

    TLBotUpdates monobotDeleteAccount(String reason, long requestId, int botId) throws
            RpcErrorException, IOException;

    TLBotUpdates monobotEditInlineBotMessage(boolean noWebpage, boolean stopGeoLive,
            TLInputBotInlineMessageID id, String message, TLAbsInputMedia media,
            TLAbsReplyMarkup replyMarkup, TLVector<TLAbsMessageEntity> entities,
            TLAbsInputGeoPoint geoPoint, long requestId, int botId) throws RpcErrorException,
            IOException;

    TLBotUpdates monobotEditMessage(boolean noWebpage, boolean stopGeoLive, TLAbsInputPeer peer,
            int id, String message, TLAbsInputMedia media, TLAbsReplyMarkup replyMarkup,
            TLVector<TLAbsMessageEntity> entities, TLAbsInputGeoPoint geoPoint, long requestId,
            int botId) throws RpcErrorException, IOException;

    TLBotUpdates monobotForwardMessages(boolean silent, boolean background, boolean withMyScore,
            boolean grouped, TLAbsInputPeer fromPeer, TLIntVector id, TLLongVector randomId,
            TLAbsInputPeer toPeer, long requestId, int botId) throws RpcErrorException, IOException;

    TLBotUpdates monobotMessagesSetTyping(TLAbsInputPeer peer, TLAbsSendMessageAction action,
            long requestId, int botId) throws RpcErrorException, IOException;

    TLBotUpdates monobotSendMedia(boolean silent, boolean background, boolean clearDraft,
            TLAbsInputPeer peer, Integer replyToMsgId, TLAbsInputMedia media, String message,
            long randomId, TLAbsReplyMarkup replyMarkup, TLVector<TLAbsMessageEntity> entities,
            long requestId, int botId) throws RpcErrorException, IOException;

    TLBotUpdates monobotSendMessage(boolean noWebpage, boolean silent, boolean background,
            boolean clearDraft, TLAbsInputPeer peer, Integer replyToMsgId, String message,
            long randomId, TLAbsReplyMarkup replyMarkup, TLVector<TLAbsMessageEntity> entities,
            long requestId, int botId) throws RpcErrorException, IOException;

    TLBotUpdates monobotSetBotCallbackAnswer(boolean alert, long queryId, String message,
            String url, int cacheTime, long requestId, int botId) throws RpcErrorException,
            IOException;

    TLBotUpdates monobotSignUp(String botName, String userName, long requestId) throws
            RpcErrorException, IOException;

    TLBotFile monobotUploadGetFile(TLAbsInputFileLocation location, int offset, int limit,
            long requestId, int botId) throws RpcErrorException, IOException;

    TLBool paymentsClearSavedInfo(boolean credentials, boolean info) throws RpcErrorException,
            IOException;

    TLPaymentForm paymentsGetPaymentForm(int msgId) throws RpcErrorException, IOException;

    TLPaymentReceipt paymentsGetPaymentReceipt(int msgId) throws RpcErrorException, IOException;

    TLSavedInfo paymentsGetSavedInfo() throws RpcErrorException, IOException;

    TLAbsPaymentResult paymentsSendPaymentForm(int msgId, String requestedInfoId,
            String shippingOptionId, TLAbsInputPaymentCredentials credentials) throws
            RpcErrorException, IOException;

    TLValidatedRequestedInfo paymentsValidateRequestedInfo(boolean save, int msgId,
            TLPaymentRequestedInfo info) throws RpcErrorException, IOException;

    TLPhoneCall phoneAcceptCall(TLInputPhoneCall peer, TLBytes gB, TLPhoneCallProtocol protocol)
            throws RpcErrorException, IOException;

    TLPhoneCall phoneConfirmCall(TLInputPhoneCall peer, TLBytes gA, long keyFingerprint,
            TLPhoneCallProtocol protocol) throws RpcErrorException, IOException;

    TLAbsUpdates phoneDiscardCall(TLInputPhoneCall peer, int duration,
            TLAbsPhoneCallDiscardReason reason, long connectionId) throws RpcErrorException,
            IOException;

    TLDataJSON phoneGetCallConfig() throws RpcErrorException, IOException;

    TLBool phoneReceivedCall(TLInputPhoneCall peer) throws RpcErrorException, IOException;

    TLPhoneCall phoneRequestCall(TLAbsInputUser userId, int randomId, TLBytes gAHash,
            TLPhoneCallProtocol protocol) throws RpcErrorException, IOException;

    TLBool phoneSaveCallDebug(TLInputPhoneCall peer, TLDataJSON debug) throws RpcErrorException,
            IOException;

    TLAbsUpdates phoneSetCallRating(TLInputPhoneCall peer, int rating, String comment) throws
            RpcErrorException, IOException;

    TLLongVector photosDeletePhotos(TLVector<TLAbsInputPhoto> id) throws RpcErrorException,
            IOException;

    TLAbsPhotos photosGetUserPhotos(TLAbsInputUser userId, int offset, long maxId, int limit) throws
            RpcErrorException, IOException;

    TLAbsUserProfilePhoto photosUpdateProfilePhoto(TLAbsInputPhoto id) throws RpcErrorException,
            IOException;

    TLPhoto photosUploadProfilePhoto(TLAbsInputFile file) throws RpcErrorException, IOException;

    TLStickerSet stickersAddStickerToSet(TLAbsInputStickerSet stickerset,
            TLInputStickerSetItem sticker) throws RpcErrorException, IOException;

    TLStickerSet stickersChangeStickerPosition(TLAbsInputDocument sticker, int position) throws
            RpcErrorException, IOException;

    TLStickerSet stickersCreateStickerSet(boolean masks, TLAbsInputUser userId, String title,
            String shortName, TLVector<TLInputStickerSetItem> stickers) throws RpcErrorException,
            IOException;

    TLStickerSet stickersRemoveStickerFromSet(TLAbsInputDocument sticker) throws RpcErrorException,
            IOException;

    TLAbsChannelDifference updatesGetChannelDifference(boolean force, TLAbsInputChannel channel,
            TLAbsChannelMessagesFilter filter, int pts, int limit) throws RpcErrorException,
            IOException;

    TLAbsDifference updatesGetDifference(int pts, Integer ptsTotalLimit, int date, int qts) throws
            RpcErrorException, IOException;

    TLState updatesGetState() throws RpcErrorException, IOException;

    TLAbsCdnFile uploadGetCdnFile(TLBytes fileToken, int offset, int limit) throws
            RpcErrorException, IOException;

    TLVector<TLFileHash> uploadGetCdnFileHashes(TLBytes fileToken, int offset) throws
            RpcErrorException, IOException;

    TLAbsFile uploadGetFile(TLAbsInputFileLocation location, int offset, int limit) throws
            RpcErrorException, IOException;

    TLVector<TLFileHash> uploadGetFileHashes(TLAbsInputFileLocation location, int offset) throws
            RpcErrorException, IOException;

    TLWebFile uploadGetWebFile(TLAbsInputWebFileLocation location, int offset, int limit) throws
            RpcErrorException, IOException;

    TLVector<TLFileHash> uploadReuploadCdnFile(TLBytes fileToken, TLBytes requestToken) throws
            RpcErrorException, IOException;

    TLBool uploadSaveBigFilePart(long fileId, int filePart, int fileTotalParts, TLBytes bytes)
            throws RpcErrorException, IOException;

    TLBool uploadSaveFilePart(long fileId, int filePart, TLBytes bytes) throws RpcErrorException,
            IOException;

    TLUserFull usersGetFullUser(TLAbsInputUser id) throws RpcErrorException, IOException;

    TLVector<TLAbsUser> usersGetUsers(TLVector<TLAbsInputUser> id) throws RpcErrorException,
            IOException;

    TLBool usersSetSecureValueErrors(TLAbsInputUser id, TLVector<TLAbsSecureValueError> errors)
            throws RpcErrorException, IOException;
}
