package io.objects.tl.api;

import static io.objects.tl.StreamUtils.*;
import static io.objects.tl.TLObjectUtils.*;

import io.objects.tl.core.TLObject;

/**
 * Abstraction level for the following constructors:
 * <ul>
 * <li>{@link TLDecryptedMessage}: decryptedMessage#91cc4674</li>
 * <li>{@link TLDecryptedMessageService}: decryptedMessageService#73164160</li>
 * </ul>
 *
 * This class is generated by Mono's TL class generator
 */
public abstract class TLAbsDecryptedMessage extends TLObject {
    protected long randomId;

    public TLAbsDecryptedMessage() {
    }

    public long getRandomId() {
        return randomId;
    }

    public void setRandomId(long randomId) {
        this.randomId = randomId;
    }
}
