package io.objects.tl.api;

import static io.objects.tl.StreamUtils.*;
import static io.objects.tl.TLObjectUtils.*;

import io.objects.tl.core.TLObject;

/**
 * Abstraction level for the following constructors:
 * <ul>
 * <li>{@link TLPeerChannel}: peerChannel#bddde532</li>
 * <li>{@link TLPeerChat}: peerChat#bad0e5bb</li>
 * <li>{@link TLPeerUser}: peerUser#9db1bc6d</li>
 * </ul>
 *
 * This class is generated by Mono's TL class generator
 */
public abstract class TLAbsPeer extends TLObject {
    public TLAbsPeer() {
    }
}
