package io.objects.tl.api;

import static io.objects.tl.StreamUtils.*;
import static io.objects.tl.TLObjectUtils.*;

import io.objects.tl.core.TLObject;

/**
 * Abstraction level for the following constructors:
 * <ul>
 * <li>{@link TLChatParticipants}: chatParticipants#3f460fed</li>
 * <li>{@link TLChatParticipantsForbidden}: chatParticipantsForbidden#fc900c2b</li>
 * </ul>
 *
 * This class is generated by Mono's TL class generator
 */
public abstract class TLAbsChatParticipants extends TLObject {
    protected int chatId;

    public TLAbsChatParticipants() {
    }

    public int getChatId() {
        return chatId;
    }

    public void setChatId(int chatId) {
        this.chatId = chatId;
    }
}
