package io.objects.tl.api;

import static io.objects.tl.StreamUtils.*;
import static io.objects.tl.TLObjectUtils.*;

import io.objects.tl.core.TLObject;

/**
 * Abstraction level for the following constructors:
 * <ul>
 * <li>{@link TLInputNotifyChats}: inputNotifyChats#4a95e84e</li>
 * <li>{@link TLInputNotifyPeer}: inputNotifyPeer#b8bc5b0c</li>
 * <li>{@link TLInputNotifyUsers}: inputNotifyUsers#193b4417</li>
 * </ul>
 *
 * This class is generated by Mono's TL class generator
 */
public abstract class TLAbsInputNotifyPeer extends TLObject {
    public TLAbsInputNotifyPeer() {
    }
}
