package io.objects.tl.api;

import static io.objects.tl.StreamUtils.*;
import static io.objects.tl.TLObjectUtils.*;

import io.objects.tl.core.TLObject;

/**
 * Abstraction level for the following constructors:
 * <ul>
 * <li>{@link TLPhoneCall}: phoneCall#ffe6ab67</li>
 * <li>{@link TLPhoneCallAccepted}: phoneCallAccepted#6d003d3f</li>
 * <li>{@link TLPhoneCallDiscarded}: phoneCallDiscarded#50ca4de1</li>
 * <li>{@link TLPhoneCallEmpty}: phoneCallEmpty#5366c915</li>
 * <li>{@link TLPhoneCallRequested}: phoneCallRequested#83761ce4</li>
 * <li>{@link TLPhoneCallWaiting}: phoneCallWaiting#1b8f4ad1</li>
 * </ul>
 *
 * This class is generated by Mono's TL class generator
 */
public abstract class TLAbsPhoneCall extends TLObject {
    protected long id;

    public TLAbsPhoneCall() {
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }
}
