package io.objects.tl.api;

import static io.objects.tl.StreamUtils.*;
import static io.objects.tl.TLObjectUtils.*;

import io.objects.tl.core.TLObject;

/**
 * Abstraction level for the following constructors:
 * <ul>
 * <li>{@link TLChatInviteEmpty}: chatInviteEmpty#69df3769</li>
 * <li>{@link TLChatInviteExported}: chatInviteExported#fc2e05bc</li>
 * </ul>
 *
 * This class is generated by Mono's TL class generator
 */
public abstract class TLAbsExportedChatInvite extends TLObject {
    public TLAbsExportedChatInvite() {
    }

    public abstract boolean isEmpty();

    public abstract boolean isNotEmpty();

    public TLChatInviteExported getAsChatInviteExported() {
        return null;
    }
}
