package io.objects.tl.api;

import static io.objects.tl.StreamUtils.*;
import static io.objects.tl.TLObjectUtils.*;

import io.objects.tl.core.TLObject;

/**
 * Abstraction level for the following constructors:
 * <ul>
 * <li>{@link TLDecryptedMessageActionAbortKey}: decryptedMessageActionAbortKey#dd05ec6b</li>
 * <li>{@link TLDecryptedMessageActionAcceptKey}: decryptedMessageActionAcceptKey#6fe1735b</li>
 * <li>{@link TLDecryptedMessageActionCommitKey}: decryptedMessageActionCommitKey#ec2e0b9b</li>
 * <li>{@link TLDecryptedMessageActionDeleteMessages}: decryptedMessageActionDeleteMessages#65614304</li>
 * <li>{@link TLDecryptedMessageActionFlushHistory}: decryptedMessageActionFlushHistory#6719e45c</li>
 * <li>{@link TLDecryptedMessageActionNoop}: decryptedMessageActionNoop#a82fdd63</li>
 * <li>{@link TLDecryptedMessageActionNotifyLayer}: decryptedMessageActionNotifyLayer#f3048883</li>
 * <li>{@link TLDecryptedMessageActionReadMessages}: decryptedMessageActionReadMessages#c4f40be</li>
 * <li>{@link TLDecryptedMessageActionRequestKey}: decryptedMessageActionRequestKey#f3c9611b</li>
 * <li>{@link TLDecryptedMessageActionResend}: decryptedMessageActionResend#511110b0</li>
 * <li>{@link TLDecryptedMessageActionScreenshotMessages}: decryptedMessageActionScreenshotMessages#8ac1f475</li>
 * <li>{@link TLDecryptedMessageActionSetMessageTTL}: decryptedMessageActionSetMessageTTL#a1733aec</li>
 * <li>{@link TLDecryptedMessageActionTyping}: decryptedMessageActionTyping#ccb27641</li>
 * </ul>
 *
 * This class is generated by Mono's TL class generator
 */
public abstract class TLAbsDecryptedMessageAction extends TLObject {
    public TLAbsDecryptedMessageAction() {
    }
}
