package io.objects.tl.api;

import static io.objects.tl.StreamUtils.*;
import static io.objects.tl.TLObjectUtils.*;

import io.objects.tl.TLContext;
import io.objects.tl.core.TLObject;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;

/**
 * This class is generated by Mono's TL class generator
 */
public class TLChannelAdminLogEvent extends TLObject {
    public static final int CONSTRUCTOR_ID = 0x3b5a3e40;

    protected long id;

    protected int date;

    protected int userId;

    protected TLAbsChannelAdminLogEventAction action;

    private final String _constructor = "channelAdminLogEvent#3b5a3e40";

    public TLChannelAdminLogEvent() {
    }

    public TLChannelAdminLogEvent(long id, int date, int userId,
            TLAbsChannelAdminLogEventAction action) {
        this.id = id;
        this.date = date;
        this.userId = userId;
        this.action = action;
    }

    @Override
    public void serializeBody(OutputStream stream) throws IOException {
        writeLong(id, stream);
        writeInt(date, stream);
        writeInt(userId, stream);
        writeTLObject(action, stream);
    }

    @Override
    @SuppressWarnings({"unchecked", "SimplifiableConditionalExpression"})
    public void deserializeBody(InputStream stream, TLContext context) throws IOException {
        id = readLong(stream);
        date = readInt(stream);
        userId = readInt(stream);
        action = readTLObject(stream, context, TLAbsChannelAdminLogEventAction.class, -1);
    }

    @Override
    public int computeSerializedSize() {
        int size = SIZE_CONSTRUCTOR_ID;
        size += SIZE_INT64;
        size += SIZE_INT32;
        size += SIZE_INT32;
        size += action.computeSerializedSize();
        return size;
    }

    @Override
    public String toString() {
        return _constructor;
    }

    @Override
    public int getConstructorId() {
        return CONSTRUCTOR_ID;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public int getDate() {
        return date;
    }

    public void setDate(int date) {
        this.date = date;
    }

    public int getUserId() {
        return userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public TLAbsChannelAdminLogEventAction getAction() {
        return action;
    }

    public void setAction(TLAbsChannelAdminLogEventAction action) {
        this.action = action;
    }
}
