package io.objects.tl.api;

import io.objects.tl.TLContext;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;

import static io.objects.tl.StreamUtils.readInt;
import static io.objects.tl.StreamUtils.writeInt;
import static io.objects.tl.TLObjectUtils.SIZE_CONSTRUCTOR_ID;
import static io.objects.tl.TLObjectUtils.SIZE_INT32;

/**
 * This class is generated by Mono's TL class generator
 */
public class TLChannelAdminRightsVtd extends TLChannelAdminRights {
    public static final int CONSTRUCTOR_ID = 0x5fb224d5;

    protected int flags;

    protected boolean changeInfo;

    protected boolean postMessages;

    protected boolean editMessages;

    protected boolean deleteMessages;

    protected boolean banUsers;

    protected boolean inviteUsers;

    protected boolean pinMessages;

    protected boolean addAdmins;

    private final String _constructor = "channelAdminRightsVtd#5fb224d5";

    public TLChannelAdminRightsVtd() {
    }

    public TLChannelAdminRightsVtd(boolean changeInfo, boolean postMessages, boolean editMessages,
                                   boolean deleteMessages, boolean banUsers, boolean inviteUsers, boolean inviteLink,
                                   boolean pinMessages, boolean addAdmins, boolean manageCall) {
        this.changeInfo = changeInfo;
        this.postMessages = postMessages;
        this.editMessages = editMessages;
        this.deleteMessages = deleteMessages;
        this.banUsers = banUsers;
        this.inviteUsers = inviteUsers;
        this.pinMessages = pinMessages;
        this.addAdmins = addAdmins;
    }

    private void computeFlags() {
        flags = 0;
        flags = changeInfo ? (flags | 1) : (flags & ~1);
        flags = postMessages ? (flags | 2) : (flags & ~2);
        flags = editMessages ? (flags | 4) : (flags & ~4);
        flags = deleteMessages ? (flags | 8) : (flags & ~8);
        flags = banUsers ? (flags | 16) : (flags & ~16);
        flags = inviteUsers ? (flags | 32) : (flags & ~32);
        flags = pinMessages ? (flags | 128) : (flags & ~128);
        flags = addAdmins ? (flags | 512) : (flags & ~512);
    }

    @Override
    public void serializeBody(OutputStream stream) throws IOException {
        computeFlags();

        writeInt(flags, stream);
    }

    @Override
    @SuppressWarnings({"unchecked", "SimplifiableConditionalExpression"})
    public void deserializeBody(InputStream stream, TLContext context) throws IOException {
        flags = readInt(stream);
        changeInfo = (flags & 1) != 0;
        postMessages = (flags & 2) != 0;
        editMessages = (flags & 4) != 0;
        deleteMessages = (flags & 8) != 0;
        banUsers = (flags & 16) != 0;
        inviteUsers = (flags & 32) != 0;
        pinMessages = (flags & 128) != 0;
        addAdmins = (flags & 512) != 0;
    }

    @Override
    public int computeSerializedSize() {
        computeFlags();

        int size = SIZE_CONSTRUCTOR_ID;
        size += SIZE_INT32;
        return size;
    }

    @Override
    public String toString() {
        return _constructor;
    }

    @Override
    public int getConstructorId() {
        return CONSTRUCTOR_ID;
    }

    public boolean getChangeInfo() {
        return changeInfo;
    }

    public void setChangeInfo(boolean changeInfo) {
        this.changeInfo = changeInfo;
    }

    public boolean getPostMessages() {
        return postMessages;
    }

    public void setPostMessages(boolean postMessages) {
        this.postMessages = postMessages;
    }

    public boolean getEditMessages() {
        return editMessages;
    }

    public void setEditMessages(boolean editMessages) {
        this.editMessages = editMessages;
    }

    public boolean getDeleteMessages() {
        return deleteMessages;
    }

    public void setDeleteMessages(boolean deleteMessages) {
        this.deleteMessages = deleteMessages;
    }

    public boolean getBanUsers() {
        return banUsers;
    }

    public void setBanUsers(boolean banUsers) {
        this.banUsers = banUsers;
    }

    public boolean getInviteUsers() {
        return inviteUsers;
    }

    public void setInviteUsers(boolean inviteUsers) {
        this.inviteUsers = inviteUsers;
    }

    public boolean getPinMessages() {
        return pinMessages;
    }

    public void setPinMessages(boolean pinMessages) {
        this.pinMessages = pinMessages;
    }

    public boolean getAddAdmins() {
        return addAdmins;
    }

    public void setAddAdmins(boolean addAdmins) {
        this.addAdmins = addAdmins;
    }
}
