package io.objects.tl.api;

import static io.objects.tl.StreamUtils.*;
import static io.objects.tl.TLObjectUtils.*;

import java.lang.Override;
import java.lang.String;

/**
 * This class is generated by Mono's TL class generator
 */
public class TLChannelAdminLogEventActionParticipantLeave extends TLAbsChannelAdminLogEventAction {
    public static final int CONSTRUCTOR_ID = 0xf89777f2;

    private final String _constructor = "channelAdminLogEventActionParticipantLeave#f89777f2";

    public TLChannelAdminLogEventActionParticipantLeave() {
    }

    @Override
    public String toString() {
        return _constructor;
    }

    @Override
    public int getConstructorId() {
        return CONSTRUCTOR_ID;
    }
}
