package io.objects.tl.api;

import static io.objects.tl.StreamUtils.*;
import static io.objects.tl.TLObjectUtils.*;

import io.objects.tl.TLContext;
import io.objects.tl.core.TLBytes;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;

/**
 * This class is generated by Mono's TL class generator
 */
public class TLDecryptedMessageMediaAudio extends TLAbsDecryptedMessageMedia {
    public static final int CONSTRUCTOR_ID = 0x57e0a9cb;

    protected int duration;

    protected String mimeType;

    protected int size;

    protected TLBytes key;

    protected TLBytes iv;

    private final String _constructor = "decryptedMessageMediaAudio#57e0a9cb";

    public TLDecryptedMessageMediaAudio() {
    }

    public TLDecryptedMessageMediaAudio(int duration, String mimeType, int size, TLBytes key,
            TLBytes iv) {
        this.duration = duration;
        this.mimeType = mimeType;
        this.size = size;
        this.key = key;
        this.iv = iv;
    }

    @Override
    public void serializeBody(OutputStream stream) throws IOException {
        writeInt(duration, stream);
        writeString(mimeType, stream);
        writeInt(size, stream);
        writeTLBytes(key, stream);
        writeTLBytes(iv, stream);
    }

    @Override
    @SuppressWarnings({"unchecked", "SimplifiableConditionalExpression"})
    public void deserializeBody(InputStream stream, TLContext context) throws IOException {
        duration = readInt(stream);
        mimeType = readTLString(stream);
        size = readInt(stream);
        key = readTLBytes(stream, context);
        iv = readTLBytes(stream, context);
    }

    @Override
    public int computeSerializedSize() {
        int size = SIZE_CONSTRUCTOR_ID;
        size += SIZE_INT32;
        size += computeTLStringSerializedSize(mimeType);
        size += SIZE_INT32;
        size += computeTLBytesSerializedSize(key);
        size += computeTLBytesSerializedSize(iv);
        return size;
    }

    @Override
    public String toString() {
        return _constructor;
    }

    @Override
    public int getConstructorId() {
        return CONSTRUCTOR_ID;
    }

    public int getDuration() {
        return duration;
    }

    public void setDuration(int duration) {
        this.duration = duration;
    }

    public String getMimeType() {
        return mimeType;
    }

    public void setMimeType(String mimeType) {
        this.mimeType = mimeType;
    }

    public int getSize() {
        return size;
    }

    public void setSize(int size) {
        this.size = size;
    }

    public TLBytes getKey() {
        return key;
    }

    public void setKey(TLBytes key) {
        this.key = key;
    }

    public TLBytes getIv() {
        return iv;
    }

    public void setIv(TLBytes iv) {
        this.iv = iv;
    }
}
