package io.objects.tl.api;

import static io.objects.tl.StreamUtils.*;
import static io.objects.tl.TLObjectUtils.*;

import java.lang.Override;
import java.lang.String;

/**
 * This class is generated by Mono's TL class generator
 */
public class TLInputPrivacyValueAllowContacts extends TLAbsInputPrivacyRule {
    public static final int CONSTRUCTOR_ID = 0xd09e07b;

    private final String _constructor = "inputPrivacyValueAllowContacts#d09e07b";

    public TLInputPrivacyValueAllowContacts() {
    }

    @Override
    public String toString() {
        return _constructor;
    }

    @Override
    public int getConstructorId() {
        return CONSTRUCTOR_ID;
    }
}
