package io.objects.tl.api;

import static io.objects.tl.StreamUtils.*;
import static io.objects.tl.TLObjectUtils.*;

import java.lang.Override;
import java.lang.String;

/**
 * This class is generated by Mono's TL class generator
 */
public class TLMessageActionEmpty extends TLAbsMessageAction {
    public static final int CONSTRUCTOR_ID = 0xb6aef7b0;

    private final String _constructor = "messageActionEmpty#b6aef7b0";

    public TLMessageActionEmpty() {
    }

    @Override
    public String toString() {
        return _constructor;
    }

    @Override
    public int getConstructorId() {
        return CONSTRUCTOR_ID;
    }
}
