package io.objects.tl.api;

import io.objects.tl.TLContext;
import io.objects.tl.core.TLLongVector;
import io.objects.tl.core.TLObject;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;

import static io.objects.tl.StreamUtils.*;

/**
 * This class is generated by Mono's TL class generator
 */
public class TLMessagesAllInfo extends TLObject {
    public static final int CONSTRUCTOR_ID = 0x8cc0d131;

    protected TLLongVector message_ids;

    protected String info;

    private final String _constructor = "messagesAllInfo#8cc0d131";

    public TLMessagesAllInfo() {
    }

    @Override
    public void serializeBody(OutputStream stream) throws IOException {
        writeTLVector(message_ids, stream);
        writeString(info, stream);
    }

    @Override
    public void deserializeBody(InputStream stream, TLContext context) throws IOException {
        message_ids = readTLLongVector(stream, context);
        info = readTLString(stream);
    }

    @Override
    public String toString() {
        return _constructor;
    }

    public TLLongVector getMessage_ids() {
        return message_ids;
    }

    public void setMessage_ids(TLLongVector message_ids) {
        this.message_ids = message_ids;
    }

    public String getInfo() {
        return info;
    }

    public void setInfo(String info) {
        this.info = info;
    }

    @Override
    public int getConstructorId() {
        return CONSTRUCTOR_ID;
    }
}
