package io.objects.tl.api;

import static io.objects.tl.StreamUtils.*;
import static io.objects.tl.TLObjectUtils.*;

import java.lang.Override;
import java.lang.String;

/**
 * This class is generated by Mono's TL class generator
 */
public class TLMessageActionPinMessage extends TLAbsMessageAction {
    public static final int CONSTRUCTOR_ID = 0x94bd38ed;

    private final String _constructor = "messageActionPinMessage#94bd38ed";

    public TLMessageActionPinMessage() {
    }

    @Override
    public String toString() {
        return _constructor;
    }

    @Override
    public int getConstructorId() {
        return CONSTRUCTOR_ID;
    }
}
