package io.objects.tl.api;

import static io.objects.tl.StreamUtils.*;
import static io.objects.tl.TLObjectUtils.*;

import java.lang.Override;
import java.lang.String;

/**
 * This class is generated by Mono's TL class generator
 */
public class TLPrivacyValueAllowContacts extends TLAbsPrivacyRule {
    public static final int CONSTRUCTOR_ID = 0xfffe1bac;

    private final String _constructor = "privacyValueAllowContacts#fffe1bac";

    public TLPrivacyValueAllowContacts() {
    }

    @Override
    public String toString() {
        return _constructor;
    }

    @Override
    public int getConstructorId() {
        return CONSTRUCTOR_ID;
    }
}
