package io.objects.tl.api;

import static io.objects.tl.StreamUtils.*;
import static io.objects.tl.TLObjectUtils.*;

import io.objects.tl.TLContext;
import io.objects.tl.core.TLVector;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;

/**
 * This class is generated by Mono's TL class generator
 */
public class TLStickerSetMultiCovered extends TLAbsStickerSetCovered {
    public static final int CONSTRUCTOR_ID = 0x3407e51b;

    protected TLVector<TLAbsDocument> covers;

    private final String _constructor = "stickerSetMultiCovered#3407e51b";

    public TLStickerSetMultiCovered() {
    }

    public TLStickerSetMultiCovered(TLAbsStickerSet set, TLVector<TLAbsDocument> covers) {
        this.set = set;
        this.covers = covers;
    }

    @Override
    public void serializeBody(OutputStream stream) throws IOException {
        writeTLObject(set, stream);
        writeTLVector(covers, stream);
    }

    @Override
    @SuppressWarnings({"unchecked", "SimplifiableConditionalExpression"})
    public void deserializeBody(InputStream stream, TLContext context) throws IOException {
        set = readTLObject(stream, context, TLAbsStickerSet.class, -1);
        covers = readTLVector(stream, context);
    }

    @Override
    public int computeSerializedSize() {
        int size = SIZE_CONSTRUCTOR_ID;
        size += set.computeSerializedSize();
        size += covers.computeSerializedSize();
        return size;
    }

    @Override
    public String toString() {
        return _constructor;
    }

    @Override
    public int getConstructorId() {
        return CONSTRUCTOR_ID;
    }

    public TLAbsStickerSet getSet() {
        return set;
    }

    public void setSet(TLAbsStickerSet set) {
        this.set = set;
    }

    public TLVector<TLAbsDocument> getCovers() {
        return covers;
    }

    public void setCovers(TLVector<TLAbsDocument> covers) {
        this.covers = covers;
    }
}
