package io.objects.tl.api.messages;

import static io.objects.tl.StreamUtils.*;
import static io.objects.tl.TLObjectUtils.*;

import io.objects.tl.core.TLObject;

/**
 * Abstraction level for the following constructors:
 * <ul>
 * <li>{@link TLFavedStickers}: messages.favedStickers#f37f2f16</li>
 * <li>{@link TLFavedStickersNotModified}: messages.favedStickersNotModified#9e8fa6d3</li>
 * </ul>
 *
 * This class is generated by Mono's TL class generator
 */
public abstract class TLAbsFavedStickers extends TLObject {
    public TLAbsFavedStickers() {
    }
}
