package io.objects.tl.api.messages;

import static io.objects.tl.StreamUtils.*;
import static io.objects.tl.TLObjectUtils.*;

import io.objects.tl.core.TLObject;

/**
 * Abstraction level for the following constructors:
 * <ul>
 * <li>{@link TLAllStickers}: messages.allStickers#edfd405f</li>
 * <li>{@link TLAllStickersNotModified}: messages.allStickersNotModified#e86602c3</li>
 * </ul>
 *
 * This class is generated by Mono's TL class generator
 */
public abstract class TLAbsAllStickers extends TLObject {
    public TLAbsAllStickers() {
    }
}
