package io.objects.tl.api.messages;

import static io.objects.tl.StreamUtils.*;
import static io.objects.tl.TLObjectUtils.*;

import io.objects.tl.core.TLObject;

/**
 * Abstraction level for the following constructors:
 * <ul>
 * <li>{@link TLStickers}: messages.stickers#e4599bbd</li>
 * <li>{@link TLStickersNotModified}: messages.stickersNotModified#f1749a22</li>
 * </ul>
 *
 * This class is generated by Mono's TL class generator
 */
public abstract class TLAbsStickers extends TLObject {
    public TLAbsStickers() {
    }
}
