package io.tlobjects.tl.api.updates;

import static io.tlobjects.tl.StreamUtils.*;
import static io.tlobjects.tl.TLObjectUtils.*;

import io.tlobjects.tl.core.TLObject;

/**
 * Abstraction level for the following constructors:
 * <ul>
 * <li>{@link TLDifference}: updates.difference#f49ca0</li>
 * <li>{@link TLDifferenceEmpty}: updates.differenceEmpty#5d75a138</li>
 * <li>{@link TLDifferenceSlice}: updates.differenceSlice#a8fb1981</li>
 * <li>{@link TLDifferenceTooLong}: updates.differenceTooLong#4afe8f6d</li>
 * </ul>
 *
 * This class is generated by Mono's TL class generator
 */
public abstract class TLAbsDifference extends TLObject {
    public TLAbsDifference() {
    }
}
