package io.tlobjects.tl.api;

import static io.tlobjects.tl.StreamUtils.*;
import static io.tlobjects.tl.TLObjectUtils.*;

import io.tlobjects.tl.core.TLObject;

/**
 * Abstraction level for the following constructors:
 * <ul>
 * <li>{@link TLEncryptedFile}: encryptedFile#4a70994c</li>
 * <li>{@link TLEncryptedFileEmpty}: encryptedFileEmpty#c21f497e</li>
 * </ul>
 *
 * This class is generated by Mono's TL class generator
 */
public abstract class TLAbsEncryptedFile extends TLObject {
    public TLAbsEncryptedFile() {
    }

    public abstract boolean isEmpty();

    public abstract boolean isNotEmpty();

    public TLEncryptedFile getAsEncryptedFile() {
        return null;
    }
}
