package io.tlobjects.tl.api;

import static io.tlobjects.tl.StreamUtils.*;
import static io.tlobjects.tl.TLObjectUtils.*;

import io.tlobjects.tl.core.TLObject;

/**
 * Abstraction level for the following constructors:
 * <ul>
 * <li>{@link TLInputWebFileGeoPointLocation}: inputWebFileGeoPointLocation#9f2221c9</li>
 * <li>{@link TLInputWebFileLocation}: inputWebFileLocation#c239d686</li>
 * </ul>
 *
 * This class is generated by Mono's TL class generator
 */
public abstract class TLAbsInputWebFileLocation extends TLObject {
    protected long accessHash;

    public TLAbsInputWebFileLocation() {
    }

    public long getAccessHash() {
        return accessHash;
    }

    public void setAccessHash(long accessHash) {
        this.accessHash = accessHash;
    }
}
