package io.tlobjects.tl.api;

import static io.tlobjects.tl.StreamUtils.*;
import static io.tlobjects.tl.TLObjectUtils.*;

import io.tlobjects.tl.core.TLObject;

/**
 * Abstraction level for the following constructors:
 * <ul>
 * <li>{@link TLNotifyChats}: notifyChats#c007cec3</li>
 * <li>{@link TLNotifyPeer}: notifyPeer#9fd40bd8</li>
 * <li>{@link TLNotifyUsers}: notifyUsers#b4c83b4c</li>
 * </ul>
 *
 * This class is generated by Mono's TL class generator
 */
public abstract class TLAbsNotifyPeer extends TLObject {
    public TLAbsNotifyPeer() {
    }
}
