package io.tlobjects.tl.api;

import static io.tlobjects.tl.StreamUtils.*;
import static io.tlobjects.tl.TLObjectUtils.*;

import io.tlobjects.tl.core.TLObject;

/**
 * Abstraction level for the following constructors:
 * <ul>
 * <li>{@link TLPhoneCallDiscardReasonBusy}: phoneCallDiscardReasonBusy#faf7e8c9</li>
 * <li>{@link TLPhoneCallDiscardReasonDisconnect}: phoneCallDiscardReasonDisconnect#e095c1a0</li>
 * <li>{@link TLPhoneCallDiscardReasonHangup}: phoneCallDiscardReasonHangup#57adc690</li>
 * <li>{@link TLPhoneCallDiscardReasonMissed}: phoneCallDiscardReasonMissed#85e42301</li>
 * </ul>
 *
 * This class is generated by Mono's TL class generator
 */
public abstract class TLAbsPhoneCallDiscardReason extends TLObject {
    public TLAbsPhoneCallDiscardReason() {
    }
}
