package io.tlobjects.tl.api;

import static io.tlobjects.tl.StreamUtils.*;
import static io.tlobjects.tl.TLObjectUtils.*;

import io.tlobjects.tl.core.TLObject;

/**
 * Abstraction level for the following constructors:
 * <ul>
 * <li>{@link TLUserStatusEmpty}: userStatusEmpty#9d05049</li>
 * <li>{@link TLUserStatusLastMonth}: userStatusLastMonth#77ebc742</li>
 * <li>{@link TLUserStatusLastWeek}: userStatusLastWeek#7bf09fc</li>
 * <li>{@link TLUserStatusOffline}: userStatusOffline#8c703f</li>
 * <li>{@link TLUserStatusOnline}: userStatusOnline#edb93949</li>
 * <li>{@link TLUserStatusRecently}: userStatusRecently#e26f42f1</li>
 * </ul>
 *
 * This class is generated by Mono's TL class generator
 */
public abstract class TLAbsUserStatus extends TLObject {
    public TLAbsUserStatus() {
    }
}
