package io.tlobjects.tl.api;

import static io.tlobjects.tl.StreamUtils.*;
import static io.tlobjects.tl.TLObjectUtils.*;

import io.tlobjects.tl.core.TLObject;

/**
 * Abstraction level for the following constructors:
 * <ul>
 * <li>{@link TLChannelParticipantsAdmins}: channelParticipantsAdmins#b4608969</li>
 * <li>{@link TLChannelParticipantsBanned}: channelParticipantsBanned#1427a5e1</li>
 * <li>{@link TLChannelParticipantsBots}: channelParticipantsBots#b0d1865b</li>
 * <li>{@link TLChannelParticipantsKicked}: channelParticipantsKicked#a3b54985</li>
 * <li>{@link TLChannelParticipantsRecent}: channelParticipantsRecent#de3f3c79</li>
 * <li>{@link TLChannelParticipantsSearch}: channelParticipantsSearch#656ac4b</li>
 * </ul>
 *
 * This class is generated by Mono's TL class generator
 */
public abstract class TLAbsChannelParticipantsFilter extends TLObject {
    public TLAbsChannelParticipantsFilter() {
    }
}
