package io.tlobjects.tl.api;

import static io.tlobjects.tl.StreamUtils.*;
import static io.tlobjects.tl.TLObjectUtils.*;

import io.tlobjects.tl.core.TLObject;

/**
 * Abstraction level for the following constructors:
 * <ul>
 * <li>{@link TLSecurePasswordKdfAlgoPBKDF2HMACSHA512iter100000}: securePasswordKdfAlgoPBKDF2HMACSHA512iter100000#bbf2dda0</li>
 * <li>{@link TLSecurePasswordKdfAlgoSHA512}: securePasswordKdfAlgoSHA512#86471d92</li>
 * <li>{@link TLSecurePasswordKdfAlgoUnknown}: securePasswordKdfAlgoUnknown#4a8537</li>
 * </ul>
 *
 * This class is generated by Mono's TL class generator
 */
public abstract class TLAbsSecurePasswordKdfAlgo extends TLObject {
    public TLAbsSecurePasswordKdfAlgo() {
    }
}
