package io.tlobjects.tl.api;

import static io.tlobjects.tl.StreamUtils.*;
import static io.tlobjects.tl.TLObjectUtils.*;

import io.tlobjects.tl.core.TLObject;

/**
 * Abstraction level for the following constructors:
 * <ul>
 * <li>{@link TLTopPeerCategoryBotsInline}: topPeerCategoryBotsInline#148677e2</li>
 * <li>{@link TLTopPeerCategoryBotsPM}: topPeerCategoryBotsPM#ab661b5b</li>
 * <li>{@link TLTopPeerCategoryChannels}: topPeerCategoryChannels#161d9628</li>
 * <li>{@link TLTopPeerCategoryCorrespondents}: topPeerCategoryCorrespondents#637b7ed</li>
 * <li>{@link TLTopPeerCategoryGroups}: topPeerCategoryGroups#bd17a14a</li>
 * <li>{@link TLTopPeerCategoryPhoneCalls}: topPeerCategoryPhoneCalls#1e76a78c</li>
 * </ul>
 *
 * This class is generated by Mono's TL class generator
 */
public abstract class TLAbsTopPeerCategory extends TLObject {
    public TLAbsTopPeerCategory() {
    }
}
