package io.tlobjects.tl.api;

import static io.tlobjects.tl.StreamUtils.*;
import static io.tlobjects.tl.TLObjectUtils.*;

import io.tlobjects.tl.core.TLObject;

/**
 * Abstraction level for the following constructors:
 * <ul>
 * <li>{@link TLInputUser}: inputUser#d8292816</li>
 * <li>{@link TLInputUserEmpty}: inputUserEmpty#b98886cf</li>
 * <li>{@link TLInputUserSelf}: inputUserSelf#f7c1b13f</li>
 * </ul>
 *
 * This class is generated by Mono's TL class generator
 */
public abstract class TLAbsInputUser extends TLObject {
    public TLAbsInputUser() {
    }
}
