package io.tlobjects.tl.api;

import static io.tlobjects.tl.StreamUtils.*;
import static io.tlobjects.tl.TLObjectUtils.*;

import io.tlobjects.tl.core.TLObject;

/**
 * Abstraction level for the following constructors:
 * <ul>
 * <li>{@link TLChatInvite}: chatInvite#db74f558</li>
 * <li>{@link TLChatInviteAlready}: chatInviteAlready#5a686d7c</li>
 * </ul>
 *
 * This class is generated by Mono's TL class generator
 */
public abstract class TLAbsChatInvite extends TLObject {
    public TLAbsChatInvite() {
    }
}
