package io.tlobjects.tl.api;

import static io.tlobjects.tl.StreamUtils.*;
import static io.tlobjects.tl.TLObjectUtils.*;

import io.tlobjects.tl.core.TLObject;

/**
 * Abstraction level for the following constructors:
 * <ul>
 * <li>{@link TLPrivacyKeyChatInvite}: privacyKeyChatInvite#500e6dfa</li>
 * <li>{@link TLPrivacyKeyPhoneCall}: privacyKeyPhoneCall#3d662b7b</li>
 * <li>{@link TLPrivacyKeyStatusTimestamp}: privacyKeyStatusTimestamp#bc2eab30</li>
 * </ul>
 *
 * This class is generated by Mono's TL class generator
 */
public abstract class TLAbsPrivacyKey extends TLObject {
    public TLAbsPrivacyKey() {
    }
}
