package io.tlobjects.tl.api;

import static io.tlobjects.tl.StreamUtils.*;
import static io.tlobjects.tl.TLObjectUtils.*;

import io.tlobjects.tl.core.TLObject;

/**
 * Abstraction level for the following constructors:
 * <ul>
 * <li>{@link TLInputStickeredMediaDocument}: inputStickeredMediaDocument#438865b</li>
 * <li>{@link TLInputStickeredMediaPhoto}: inputStickeredMediaPhoto#4a992157</li>
 * </ul>
 *
 * This class is generated by Mono's TL class generator
 */
public abstract class TLAbsInputStickeredMedia extends TLObject {
    public TLAbsInputStickeredMedia() {
    }
}
