package io.tlobjects.tl.api;

import static io.tlobjects.tl.StreamUtils.*;
import static io.tlobjects.tl.TLObjectUtils.*;

import io.tlobjects.tl.core.TLObject;

/**
 * Abstraction level for the following constructors:
 * <ul>
 * <li>{@link TLStickerSetCovered}: stickerSetCovered#6410a5d2</li>
 * <li>{@link TLStickerSetMultiCovered}: stickerSetMultiCovered#3407e51b</li>
 * </ul>
 *
 * This class is generated by Mono's TL class generator
 */
public abstract class TLAbsStickerSetCovered extends TLObject {
    protected TLStickerSet set;

    public TLAbsStickerSetCovered() {
    }

    public TLStickerSet getSet() {
        return set;
    }

    public void setSet(TLStickerSet set) {
        this.set = set;
    }
}
