package io.tlobjects.tl.api;

import static io.tlobjects.tl.StreamUtils.*;
import static io.tlobjects.tl.TLObjectUtils.*;

import java.lang.Override;
import java.lang.String;

/**
 * This class is generated by Mono's TL class generator
 */
public class TLChannelParticipantsBots extends TLAbsChannelParticipantsFilter {
    public static final int CONSTRUCTOR_ID = 0xb0d1865b;

    private final String _constructor = "channelParticipantsBots#b0d1865b";

    public TLChannelParticipantsBots() {
    }

    @Override
    public String toString() {
        return _constructor;
    }

    @Override
    public int getConstructorId() {
        return CONSTRUCTOR_ID;
    }
}
