package io.tlobjects.tl.api;

import static io.tlobjects.tl.StreamUtils.*;
import static io.tlobjects.tl.TLObjectUtils.*;

import java.lang.Override;
import java.lang.String;

/**
 * This class is generated by Mono's TL class generator
 */
public class TLInputNotifyUsers extends TLAbsInputNotifyPeer {
    public static final int CONSTRUCTOR_ID = 0x193b4417;

    private final String _constructor = "inputNotifyUsers#193b4417";

    public TLInputNotifyUsers() {
    }

    @Override
    public String toString() {
        return _constructor;
    }

    @Override
    public int getConstructorId() {
        return CONSTRUCTOR_ID;
    }
}
