package io.tlobjects.tl.api;

import static io.tlobjects.tl.StreamUtils.*;
import static io.tlobjects.tl.TLObjectUtils.*;

import java.lang.Override;
import java.lang.String;

/**
 * This class is generated by Mono's TL class generator
 */
public class TLInputPeerEmpty extends TLAbsInputPeer {
    public static final int CONSTRUCTOR_ID = 0x7f3b18ea;

    private final String _constructor = "inputPeerEmpty#7f3b18ea";

    public TLInputPeerEmpty() {
    }

    @Override
    public String toString() {
        return _constructor;
    }

    @Override
    public int getConstructorId() {
        return CONSTRUCTOR_ID;
    }
}
