package io.tlobjects.tl.api;

import static io.tlobjects.tl.StreamUtils.*;
import static io.tlobjects.tl.TLObjectUtils.*;

import java.lang.Override;
import java.lang.String;

/**
 * This class is generated by Mono's TL class generator
 */
public class TLInputReportReasonPornography extends TLAbsReportReason {
    public static final int CONSTRUCTOR_ID = 0x2e59d922;

    private final String _constructor = "inputReportReasonPornography#2e59d922";

    public TLInputReportReasonPornography() {
    }

    @Override
    public String toString() {
        return _constructor;
    }

    @Override
    public int getConstructorId() {
        return CONSTRUCTOR_ID;
    }
}
