package io.tlobjects.tl.api;

import static io.tlobjects.tl.StreamUtils.*;
import static io.tlobjects.tl.TLObjectUtils.*;

import java.lang.Override;
import java.lang.String;

/**
 * This class is generated by Mono's TL class generator
 */
public class TLNotifyChats extends TLAbsNotifyPeer {
    public static final int CONSTRUCTOR_ID = 0xc007cec3;

    private final String _constructor = "notifyChats#c007cec3";

    public TLNotifyChats() {
    }

    @Override
    public String toString() {
        return _constructor;
    }

    @Override
    public int getConstructorId() {
        return CONSTRUCTOR_ID;
    }
}
