package io.tlobjects.tl.api;

import static io.tlobjects.tl.StreamUtils.*;
import static io.tlobjects.tl.TLObjectUtils.*;

import java.lang.Override;
import java.lang.String;

/**
 * This class is generated by Mono's TL class generator
 */
public class TLPageBlockUnsupported extends TLAbsPageBlock {
    public static final int CONSTRUCTOR_ID = 0x13567e8a;

    private final String _constructor = "pageBlockUnsupported#13567e8a";

    public TLPageBlockUnsupported() {
    }

    @Override
    public String toString() {
        return _constructor;
    }

    @Override
    public int getConstructorId() {
        return CONSTRUCTOR_ID;
    }
}
