package io.tlobjects.tl.api;

import static io.tlobjects.tl.StreamUtils.*;
import static io.tlobjects.tl.TLObjectUtils.*;

import io.tlobjects.tl.TLContext;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;

/**
 * This class is generated by Mono's TL class generator
 */
public class TLUpdateDialogPinned extends TLAbsUpdate {
    public static final int CONSTRUCTOR_ID = 0x19d27f3c;

    protected int flags;

    protected boolean pinned;

    protected TLDialogPeer peer;

    private final String _constructor = "updateDialogPinned#19d27f3c";

    public TLUpdateDialogPinned() {
    }

    public TLUpdateDialogPinned(boolean pinned, TLDialogPeer peer) {
        this.pinned = pinned;
        this.peer = peer;
    }

    private void computeFlags() {
        flags = 0;
        flags = pinned ? (flags | 1) : (flags & ~1);
    }

    @Override
    public void serializeBody(OutputStream stream) throws IOException {
        computeFlags();

        writeInt(flags, stream);
        writeTLObject(peer, stream);
    }

    @Override
    @SuppressWarnings({"unchecked", "SimplifiableConditionalExpression"})
    public void deserializeBody(InputStream stream, TLContext context) throws IOException {
        flags = readInt(stream);
        pinned = (flags & 1) != 0;
        peer = readTLObject(stream, context, TLDialogPeer.class, TLDialogPeer.CONSTRUCTOR_ID);
    }

    @Override
    public int computeSerializedSize() {
        computeFlags();

        int size = SIZE_CONSTRUCTOR_ID;
        size += SIZE_INT32;
        size += peer.computeSerializedSize();
        return size;
    }

    @Override
    public String toString() {
        return _constructor;
    }

    @Override
    public int getConstructorId() {
        return CONSTRUCTOR_ID;
    }

    public boolean getPinned() {
        return pinned;
    }

    public void setPinned(boolean pinned) {
        this.pinned = pinned;
    }

    public TLDialogPeer getPeer() {
        return peer;
    }

    public void setPeer(TLDialogPeer peer) {
        this.peer = peer;
    }
}
