package io.tlobjects.tl.api;

import static io.tlobjects.tl.StreamUtils.*;
import static io.tlobjects.tl.TLObjectUtils.*;

import java.lang.Override;
import java.lang.String;

/**
 * This class is generated by Mono's TL class generator
 */
public class TLUpdateReadFeaturedStickers extends TLAbsUpdate {
    public static final int CONSTRUCTOR_ID = 0x571d2742;

    private final String _constructor = "updateReadFeaturedStickers#571d2742";

    public TLUpdateReadFeaturedStickers() {
    }

    @Override
    public String toString() {
        return _constructor;
    }

    @Override
    public int getConstructorId() {
        return CONSTRUCTOR_ID;
    }
}
