package io.tlobjects.tl.api;

import static io.tlobjects.tl.StreamUtils.*;
import static io.tlobjects.tl.TLObjectUtils.*;

import java.lang.Override;
import java.lang.String;

/**
 * This class is generated by Mono's TL class generator
 */
public class TLUserStatusEmpty extends TLAbsUserStatus {
    public static final int CONSTRUCTOR_ID = 0x9d05049;

    private final String _constructor = "userStatusEmpty#9d05049";

    public TLUserStatusEmpty() {
    }

    @Override
    public String toString() {
        return _constructor;
    }

    @Override
    public int getConstructorId() {
        return CONSTRUCTOR_ID;
    }
}
