package io.tlobjects.tl.api.contacts;

import static io.tlobjects.tl.StreamUtils.*;
import static io.tlobjects.tl.TLObjectUtils.*;

import io.tlobjects.tl.core.TLObject;

/**
 * Abstraction level for the following constructors:
 * <ul>
 * <li>{@link TLContacts}: contacts.contacts#eae87e42</li>
 * <li>{@link TLContactsNotModified}: contacts.contactsNotModified#b74ba9d2</li>
 * </ul>
 *
 * This class is generated by Mono's TL class generator
 */
public abstract class TLAbsContacts extends TLObject {
    public TLAbsContacts() {
    }
}
