package io.objects.tl.api.auth;

import static io.objects.tl.StreamUtils.*;
import static io.objects.tl.TLObjectUtils.*;

import io.objects.tl.core.TLObject;

/**
 * Abstraction level for the following constructors:
 * <ul>
 * <li>{@link TLSentCodeTypeApp}: auth.sentCodeTypeApp#3dbb5986</li>
 * <li>{@link TLSentCodeTypeCall}: auth.sentCodeTypeCall#5353e5a7</li>
 * <li>{@link TLSentCodeTypeFlashCall}: auth.sentCodeTypeFlashCall#ab03c6d9</li>
 * <li>{@link TLSentCodeTypeSms}: auth.sentCodeTypeSms#c000bba2</li>
 * </ul>
 *
 * This class is generated by Mono's TL class generator
 */
public abstract class TLAbsSentCodeType extends TLObject {
    public TLAbsSentCodeType() {
    }
}
