package io.objects.tl.api.storage;

import static io.objects.tl.StreamUtils.*;
import static io.objects.tl.TLObjectUtils.*;

import java.lang.Override;
import java.lang.String;

/**
 * This class is generated by Mono's TL class generator
 */
public class TLFilePartial extends TLAbsFileType {
    public static final int CONSTRUCTOR_ID = 0x40bc6f52;

    private final String _constructor = "storage.filePartial#40bc6f52";

    public TLFilePartial() {
    }

    @Override
    public String toString() {
        return _constructor;
    }

    @Override
    public int getConstructorId() {
        return CONSTRUCTOR_ID;
    }
}
